/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package definicao_forma_pgto_controle;

import OS.OS;
import OS_Forma_de_Pagamento.Bean_OS_Contas_Disponiveis;
import OS_Forma_de_Pagamento.Bean_OS_Forma_de_Pagamento;
import OS_Forma_de_Pagamento.Bean_OS_TipoDeDocumento;
import definicao_forma_pgto.OS_Definir_Forma_de_Pagamento;
import definicao_forma_pgto_parcelas.Preenchimento_Lista_Parcelas;
import definicao_forma_pgto_parcelas_adicionar.Get_Preenchimento_Lista_Parcelas_Setado;
import definicao_forma_pgto_parcelas.Bean_Parcelas;
import home.Home;
import java.util.Date;
import java.util.List;
import javax.swing.BoxLayout;
import utilidades.JOptionPaneMod;

/**
 *
 * @author ana
 */
public class Parcelas_OS_Definir_Forma_de_Pagamento extends javax.swing.JPanel {

    OS OS;
    Home Home;
    OS_Definir_Forma_de_Pagamento OS_Definir_Forma_de_Pagamento;
    
    float Total;        
    Bean_OS_Contas_Disponiveis Bean_Conta;        
    Bean_OS_TipoDeDocumento    Bean_Documento;        
    Bean_OS_Forma_de_Pagamento Bean_Forma_Pgto;
    
    /**
     * Creates new form OS_Corpo_Adicionar_Produto
     * @param Home2
     * @param OS2
     * @param OS_Definir_Forma_de_Pagamento2
     * @param Total2
     * @param Bean_Conta2
     * @param Bean_Documento2
     * @param Bean_Forma_Pgto2
     */
    
    public Parcelas_OS_Definir_Forma_de_Pagamento( 
            Home Home2, OS OS2, OS_Definir_Forma_de_Pagamento OS_Definir_Forma_de_Pagamento2,
            float Total2, 
            Bean_OS_Contas_Disponiveis Bean_Conta2,
            Bean_OS_TipoDeDocumento Bean_Documento2, 
            Bean_OS_Forma_de_Pagamento Bean_Forma_Pgto2 ) {
        
        OS = OS2;
        Home = Home2;
        OS_Definir_Forma_de_Pagamento = OS_Definir_Forma_de_Pagamento2;
        
        Total           = Total2;        
        Bean_Conta      = Bean_Conta2;        
        Bean_Documento  = Bean_Documento2;        
        Bean_Forma_Pgto = Bean_Forma_Pgto2;
        
        initComponents();
        
        jpLista.setLayout(new BoxLayout( jpLista, BoxLayout.Y_AXIS)); 
        
        setarParcelas();
    }
                
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jpLista = new javax.swing.JPanel();

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jpLista.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpListaLayout = new javax.swing.GroupLayout(jpLista);
        jpLista.setLayout(jpListaLayout);
        jpListaLayout.setHorizontalGroup(
            jpListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );
        jpListaLayout.setVerticalGroup(
            jpListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpLista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jpLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 217, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel11;
    public javax.swing.JPanel jpLista;
    // End of variables declaration//GEN-END:variables

    private void setarParcelas(){
        
        /*
        System.out.println( Bean_Conta.getID() );
        System.out.println( Bean_Conta.getAPELIDOCURTO() );
        System.out.println( Bean_Conta.getNOMEDESCRICAODACONTA() );

        System.out.println( "\n" );
        
        System.out.println( Bean_Documento.getID() );
        System.out.println( Bean_Documento.getNOME() );
        System.out.println( Bean_Documento.getTIPODECUSTO() );
        System.out.println( Bean_Documento.getVALORDECUSTO() );
        
        System.out.println( "\n" );
        
        System.out.println( Bean_Forma_Pgto.getID() );
        System.out.println( Bean_Forma_Pgto.getNOME() );
        System.out.println( Bean_Forma_Pgto.getPARCELAMENTOMAXIMO() );
        System.out.println( Bean_Forma_Pgto.getPARCELASSEMJUROS() );
        System.out.println( Bean_Forma_Pgto.getJUROSPORCENTAGEM() );
        System.out.println( Bean_Forma_Pgto.getTAXAFIXA() );
        System.out.println( Bean_Forma_Pgto.getDESCONTOAVISTAPORCENTAGEM() );
        System.out.println( Bean_Forma_Pgto.getCONTADEDESTINOPADRAOID() );
        System.out.println( Bean_Forma_Pgto.getTIPODEDOCUMENTOPADRAOID() );
        System.out.println( Bean_Forma_Pgto.getINTERVALOPADRAOENTREASPARCELAS() );
        System.out.println( Bean_Forma_Pgto.getINTERVALOPADRAOENTREASPARCELASDIAOUMES() );
        System.out.println( "\n" );    
        */
        
        OS.listaPreenchimento_Lista_Parcelas.clear();
        
        int QTDPARCELAS = OS.pegar_e_GetQTDParcelas();
        //System.out.println("QTDPARCELAS****************************************   " + QTDPARCELAS );
        
        setar( 
            QTDPARCELAS,
            Home, OS, OS_Definir_Forma_de_Pagamento,
            Total, 
            Bean_Conta,
            Bean_Documento, 
            Bean_Forma_Pgto );                        
    }
    
    private void setar( 
            int qtdParc,
            Home Home2, OS OS2, OS_Definir_Forma_de_Pagamento OS_Definir_Forma_de_Pagamento2,
            float Total2, 
            Bean_OS_Contas_Disponiveis Bean_Conta2,
            Bean_OS_TipoDeDocumento Bean_Documento2, 
            Bean_OS_Forma_de_Pagamento Bean_Forma_Pgto2 ) {
        
        
        Control_Parcelas_Listar Control = new Control_Parcelas_Listar();
        
        List<Bean_Parcelas> Bean_Parcelas = Control.listar( 
            qtdParc,
            Home2, OS2, OS_Definir_Forma_de_Pagamento2,
            Total2, 
            Bean_Conta2,
            Bean_Documento2, 
            Bean_Forma_Pgto2 );
        
                
        mostrarLista( Bean_Parcelas );
    }
    
    protected void mostrarLista( List<Bean_Parcelas> Bean_Parcelas ){
      
        float valorParc = 0;
        for (int i = 0; i < Bean_Parcelas.size(); i++){ 
                     
            valorParc = Bean_Parcelas.get(i).getVALOR();
            adicionarParcelasAoArray( 
                    
                Bean_Parcelas.get(i).getTIPODEVALOR(), 
                Bean_Parcelas.get(i).getVALOR(),
                Bean_Parcelas.get(i).getDATADOPAGAMENTO(),  
                Bean_Parcelas.get(i).getCONTADEDESTINO(), 
                Bean_Parcelas.get(i).getTIPODEDOCUMENTO(), 
                Bean_Parcelas.get(i).getNUMERODODOCUMENTO(), 
                Bean_Parcelas.get(i).getCUSTOINTERNO() 
            );
  
        }
        
        Controle_Setar_LBS Setar_LBS = new Controle_Setar_LBS( Home, OS, OS_Definir_Forma_de_Pagamento, valorParc );           
    }
    
    private void adicionarParcelasAoArray( 
            String TIPODEVALOR, 
            float  VALOR,
            Date   DATADOPAGAMENTO,  
            int    CONTADEDESTINO, 
            int    TIPODEDOCUMENTO, 
            String NUMERODODOCUMENTO, 
            float  CUSTOINTERNO ) {
        
        try { 
            
            Preenchimento_Lista_Parcelas Preenchimento_Lista_Parcelas;
            
            Get_Preenchimento_Lista_Parcelas_Setado GetParcelas = new Get_Preenchimento_Lista_Parcelas_Setado();
            
            Preenchimento_Lista_Parcelas = GetParcelas.jpLista( OS, Home, 
                    TIPODEVALOR, VALOR, DATADOPAGAMENTO, CONTADEDESTINO, TIPODEDOCUMENTO, NUMERODODOCUMENTO, CUSTOINTERNO
            );
                        
            OS.listaPreenchimento_Lista_Parcelas.add( Preenchimento_Lista_Parcelas );        
            this.jpLista.add(  Preenchimento_Lista_Parcelas ); 
        
        }catch(Exception e) {
            JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Parcelas_OS_Definir_Forma_de_Pagamento, "
                    + "\nadicionarParcelasAoArray"
                    + e.getMessage()
                    + "\n", "adicionarParcelasAoArray" );
        }
    }

}
