/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package definicao_forma_pgto_parcelas;

import OS.OS;
import home.Home;
import java.awt.Color;
import java.util.Date;

/**
 *
 * @author ana
 */
public class Preenchimento_Lista_Parcelas extends javax.swing.JPanel {

    /**
     * Creates new form Preencher_Definicao_da_Forma_de_Pagamento2
     */
    public String TIPODEVALOR                              = "";   
    public float  VALOR                                        ;
    public Date   DATADOPAGAMENTO                              ;
    
    public int    CONTADEDESTINO                               ;    
    public int    TIPODEDOCUMENTO                              ;
    
    public String NUMERODODOCUMENTO                        = "";
    public float  CUSTOINTERNO                                 ;

    public Preenchimento_Lista_Parcelas( OS OS2, Home Home2, String TIPODEVALOR2, float VALOR2, 
            Date   DATADOPAGAMENTO2,  int    CONTADEDESTINO2, 
            int    TIPODEDOCUMENTO2, String NUMERODODOCUMENTO2, float  CUSTOINTERNO2 ) {
        
        initComponents();
        
        TIPODEVALOR       = TIPODEVALOR2;   
        VALOR             = VALOR2;
        DATADOPAGAMENTO   = DATADOPAGAMENTO2;
        
        CONTADEDESTINO    = CONTADEDESTINO2;    
        TIPODEDOCUMENTO   = TIPODEDOCUMENTO2;
        
        NUMERODODOCUMENTO = NUMERODODOCUMENTO2;
        CUSTOINTERNO      = CUSTOINTERNO2;     
                
        cbCONTADEDESTINO.setBackground( new Color( 255, 255, 255 ) );
        cbTIPODEDOCUMENTO.setBackground( new Color( 255, 255, 255 ) );
                        
        /*
        System.out.println( "\nPreenchimento_Lista_Parcelas" );
        System.out.println( "TIPODEVALOR                 " + TIPODEVALOR2 );
        System.out.println( "VALOR2                      " + VALOR2 );
        System.out.println( "DATADOPAGAMENTO             " + DATADOPAGAMENTO2 );
        System.out.println( "CONTADEDESTINO              " + CONTADEDESTINO2 );
        System.out.println( "TIPODEDOCUMENTO             " + TIPODEDOCUMENTO2 );
        System.out.println( "NUMERODODOCUMENTO           " + NUMERODODOCUMENTO2 );
        System.out.println( "CUSTOINTERNO2               " + CUSTOINTERNO2 );
        System.out.println( "Preenchimento_Lista_Parcelas\n" );*/
    }
    
    java.awt.Color amarelo = new java.awt.Color( 255,255,204 );
    java.awt.Color branco = new java.awt.Color( 255,255,255 );

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfVALOR = new javax.swing.JTextField();
        tfDATADOPAGAMENTO = new javax.swing.JTextField();
        cbCONTADEDESTINO = new javax.swing.JComboBox();
        cbTIPODEDOCUMENTO = new javax.swing.JComboBox();
        tfNUMERODODOCUMENTO = new javax.swing.JTextField();
        tfCUSTOINTERNO = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(802, 300));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        tfVALOR.setEditable(false);
        tfVALOR.setBackground(new java.awt.Color(255, 255, 255));
        tfVALOR.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfVALOR.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfVALOR.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfVALOR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfVALORMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfVALORMouseExited(evt);
            }
        });

        tfDATADOPAGAMENTO.setEditable(false);
        tfDATADOPAGAMENTO.setBackground(new java.awt.Color(255, 255, 255));
        tfDATADOPAGAMENTO.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfDATADOPAGAMENTO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDATADOPAGAMENTO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfDATADOPAGAMENTO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfDATADOPAGAMENTOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfDATADOPAGAMENTOMouseExited(evt);
            }
        });

        cbCONTADEDESTINO.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbCONTADEDESTINO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        cbCONTADEDESTINO.setPreferredSize(new java.awt.Dimension(219, 23));
        cbCONTADEDESTINO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbCONTADEDESTINOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbCONTADEDESTINOMouseExited(evt);
            }
        });

        cbTIPODEDOCUMENTO.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbTIPODEDOCUMENTO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        cbTIPODEDOCUMENTO.setPreferredSize(new java.awt.Dimension(219, 23));
        cbTIPODEDOCUMENTO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbTIPODEDOCUMENTOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbTIPODEDOCUMENTOMouseExited(evt);
            }
        });

        tfNUMERODODOCUMENTO.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfNUMERODODOCUMENTO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfNUMERODODOCUMENTO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfNUMERODODOCUMENTOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfNUMERODODOCUMENTOMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfNUMERODODOCUMENTOMousePressed(evt);
            }
        });
        tfNUMERODODOCUMENTO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNUMERODODOCUMENTOFocusLost(evt);
            }
        });

        tfCUSTOINTERNO.setEditable(false);
        tfCUSTOINTERNO.setBackground(new java.awt.Color(255, 255, 255));
        tfCUSTOINTERNO.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfCUSTOINTERNO.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfCUSTOINTERNO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfCUSTOINTERNO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfCUSTOINTERNOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfCUSTOINTERNOMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfVALOR, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDATADOPAGAMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCONTADEDESTINO, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTIPODEDOCUMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNUMERODODOCUMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCUSTOINTERNO, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfVALOR, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDATADOPAGAMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCONTADEDESTINO, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTIPODEDOCUMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNUMERODODOCUMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCUSTOINTERNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 273, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbCONTADEDESTINO, cbTIPODEDOCUMENTO, tfCUSTOINTERNO, tfDATADOPAGAMENTO, tfNUMERODODOCUMENTO, tfVALOR});

    }// </editor-fold>//GEN-END:initComponents

    private void tfVALORMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfVALORMouseEntered
        this.setBackground( amarelo );
    }//GEN-LAST:event_tfVALORMouseEntered

    private void tfVALORMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfVALORMouseExited
        this.setBackground( branco );
    }//GEN-LAST:event_tfVALORMouseExited

    private void tfDATADOPAGAMENTOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfDATADOPAGAMENTOMouseEntered
        this.setBackground( amarelo );
    }//GEN-LAST:event_tfDATADOPAGAMENTOMouseEntered

    private void tfDATADOPAGAMENTOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfDATADOPAGAMENTOMouseExited
        this.setBackground( branco );
    }//GEN-LAST:event_tfDATADOPAGAMENTOMouseExited

    private void cbCONTADEDESTINOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCONTADEDESTINOMouseEntered
        this.setBackground( amarelo );
    }//GEN-LAST:event_cbCONTADEDESTINOMouseEntered

    private void cbCONTADEDESTINOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCONTADEDESTINOMouseExited
        this.setBackground( branco );
    }//GEN-LAST:event_cbCONTADEDESTINOMouseExited

    private void cbTIPODEDOCUMENTOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTIPODEDOCUMENTOMouseEntered
        this.setBackground( amarelo );
    }//GEN-LAST:event_cbTIPODEDOCUMENTOMouseEntered

    private void cbTIPODEDOCUMENTOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTIPODEDOCUMENTOMouseExited
        this.setBackground( branco );
    }//GEN-LAST:event_cbTIPODEDOCUMENTOMouseExited

    private void tfNUMERODODOCUMENTOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNUMERODODOCUMENTOMouseEntered
        this.setBackground( amarelo );
    }//GEN-LAST:event_tfNUMERODODOCUMENTOMouseEntered

    private void tfNUMERODODOCUMENTOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNUMERODODOCUMENTOMouseExited
        this.setBackground( branco );
    }//GEN-LAST:event_tfNUMERODODOCUMENTOMouseExited

    private void tfCUSTOINTERNOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCUSTOINTERNOMouseEntered
        this.setBackground( amarelo );
    }//GEN-LAST:event_tfCUSTOINTERNOMouseEntered

    private void tfCUSTOINTERNOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCUSTOINTERNOMouseExited
        this.setBackground( branco );
    }//GEN-LAST:event_tfCUSTOINTERNOMouseExited

    private void tfNUMERODODOCUMENTOFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNUMERODODOCUMENTOFocusLost
        NUMERODODOCUMENTO = tfNUMERODODOCUMENTO.getText().trim();
    }//GEN-LAST:event_tfNUMERODODOCUMENTOFocusLost

    private void tfNUMERODODOCUMENTOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNUMERODODOCUMENTOMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNUMERODODOCUMENTOMousePressed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        this.setBackground( amarelo );
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.setBackground( branco );
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox cbCONTADEDESTINO;
    public javax.swing.JComboBox cbTIPODEDOCUMENTO;
    public javax.swing.JTextField tfCUSTOINTERNO;
    public javax.swing.JTextField tfDATADOPAGAMENTO;
    public javax.swing.JTextField tfNUMERODODOCUMENTO;
    public javax.swing.JTextField tfVALOR;
    // End of variables declaration//GEN-END:variables
}
