/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package home_controle;

import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.ImageIcon;

/**
 *
 * @author AnaMariana
 */
public class PnTabImagemHome extends javax.swing.JPanel {

    /**
     * Creates new form PnTabI9
     */
    public PnTabImagemHome() {
        initComponents();
    }
    
    ImageIcon fundo = new ImageIcon(getClass().getResource("/imagens_tela/imagem_home_1.JPG"));  
    
    @Override
    protected void paintComponent(Graphics g) {  
        super.paintComponent(g);  
        Graphics2D g2d = (Graphics2D) g.create();  
        g2d.drawImage(fundo.getImage(), 0, 0, this.getWidth(), this.getHeight(), null);  
        g2d.dispose();  
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
