/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package OS_Designer;

import OS.OS;
import OS_Controle.Controle_Inserir_Produto_Thread;
import OS_Controle.Controle_Inserir_Servico_Thread;
import OS_Produtos.BookInfoProdutos;
import OS_Servicos.BookInfoServicos;
import home.Home;
import java.awt.event.KeyEvent;
import utilidades.JOptionPaneMod;

/**
 *
 * @author ana
 */
public class Controle_De_Inserir extends javax.swing.JPanel {

    /**
     * Creates new form OS_Botoes
     * @param Home2
     * @param OS2
     */
    public Controle_De_Inserir( Home Home2, OS OS2 ) {
        initComponents();
        
        Home = Home2;
        OS  = OS2;
        
        tabInicio( false );
                
    }
    
    OS OS;
    Home Home;
    
    private void tabInicio( boolean b ){
        try { 
                    
            tabOS_Corpo_Adicionar_Controle.setEnabledAt( 0, b );
            tabOS_Corpo_Adicionar_Controle.setEnabledAt( 1, b );

        }catch(Exception e) { }
    }
    
    public void alterarTabInicio( boolean b ){
        try { 
                    
            tabOS_Corpo_Adicionar_Controle.setEnabledAt( 0, b );
            tabOS_Corpo_Adicionar_Controle.setEnabledAt( 1, b );

        }catch(Exception e) { }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabOS_Corpo_Adicionar_Controle = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btInserir = new javax.swing.JButton();
        cbAdicionar = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        tfObservacoesAdicionais = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lbAdicionar = new javax.swing.JLabel();
        ftfQuantidade = new javax.swing.JTextField();
        ftfPrecoUnitario = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btInserir1 = new javax.swing.JButton();
        cbInserirProduto = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        tfObservacoesAdicionaisProduto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lbAdicionar1 = new javax.swing.JLabel();
        ftfQuantidadeProduto = new javax.swing.JTextField();
        ftfPrecoUnitarioProduto = new javax.swing.JTextField();

        setBackground(new java.awt.Color(85, 114, 235));

        tabOS_Corpo_Adicionar_Controle.setForeground(new java.awt.Color(255, 153, 0));
        tabOS_Corpo_Adicionar_Controle.setAlignmentX(0.0F);
        tabOS_Corpo_Adicionar_Controle.setAlignmentY(0.0F);
        tabOS_Corpo_Adicionar_Controle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tabOS_Corpo_Adicionar_Controle.setPreferredSize(new java.awt.Dimension(459, 141));
        tabOS_Corpo_Adicionar_Controle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabOS_Corpo_Adicionar_ControleMousePressed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Quant.");

        btInserir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btInserir.setText("Inserir");
        btInserir.setPreferredSize(new java.awt.Dimension(83, 25));
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        cbAdicionar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cbAdicionar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        cbAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAdicionarActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("Preço unit.");

        tfObservacoesAdicionais.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfObservacoesAdicionais.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfObservacoesAdicionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfObservacoesAdicionaisActionPerformed(evt);
            }
        });
        tfObservacoesAdicionais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfObservacoesAdicionaisKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Observações adicionais");

        lbAdicionar.setText("Adicionar Serviço");

        ftfQuantidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ftfQuantidade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        ftfQuantidade.setPreferredSize(new java.awt.Dimension(79, 22));
        ftfQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftfQuantidadeKeyPressed(evt);
            }
        });

        ftfPrecoUnitario.setEditable(false);
        ftfPrecoUnitario.setBackground(new java.awt.Color(255, 255, 255));
        ftfPrecoUnitario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ftfPrecoUnitario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        ftfPrecoUnitario.setPreferredSize(new java.awt.Dimension(79, 22));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbAdicionar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftfQuantidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ftfPrecoUnitario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tfObservacoesAdicionais, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAdicionar)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbAdicionar)
                    .addComponent(ftfQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(ftfPrecoUnitario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfObservacoesAdicionais, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btInserir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabOS_Corpo_Adicionar_Controle.addTab(" Adicionar serviço", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Quant.");

        btInserir1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btInserir1.setText("Inserir");
        btInserir1.setPreferredSize(new java.awt.Dimension(83, 25));
        btInserir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserir1ActionPerformed(evt);
            }
        });

        cbInserirProduto.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cbInserirProduto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        cbInserirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbInserirProdutoActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("Preço unit.");

        tfObservacoesAdicionaisProduto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfObservacoesAdicionaisProduto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfObservacoesAdicionaisProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfObservacoesAdicionaisProdutoActionPerformed(evt);
            }
        });
        tfObservacoesAdicionaisProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfObservacoesAdicionaisProdutoKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Observações adicionais");

        lbAdicionar1.setText("Adicionar Produtos");

        ftfQuantidadeProduto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ftfQuantidadeProduto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        ftfQuantidadeProduto.setPreferredSize(new java.awt.Dimension(79, 22));
        ftfQuantidadeProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftfQuantidadeProdutoKeyPressed(evt);
            }
        });

        ftfPrecoUnitarioProduto.setEditable(false);
        ftfPrecoUnitarioProduto.setBackground(new java.awt.Color(255, 255, 255));
        ftfPrecoUnitarioProduto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ftfPrecoUnitarioProduto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        ftfPrecoUnitarioProduto.setPreferredSize(new java.awt.Dimension(79, 22));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbInserirProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbAdicionar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftfQuantidadeProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ftfPrecoUnitarioProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(tfObservacoesAdicionaisProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btInserir1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAdicionar1)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbInserirProduto)
                    .addComponent(ftfQuantidadeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(ftfPrecoUnitarioProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(1, 1, 1)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfObservacoesAdicionaisProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btInserir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabOS_Corpo_Adicionar_Controle.addTab(" Adicionar Produto", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabOS_Corpo_Adicionar_Controle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabOS_Corpo_Adicionar_Controle, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed

        Controle_Inserir_Servico_Thread t1 = new Controle_Inserir_Servico_Thread( Home, OS, OS.OS_Corpo );

        t1.setName("Controle_Inserir_Serviço_Thread");

        t1.start();
    }//GEN-LAST:event_btInserirActionPerformed

    private void cbAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAdicionarActionPerformed
        try{
            //MeuObjeto obj = (MeuObjeto) combobox.getSelectedItem();
            if( cbAdicionar.getSelectedItem() != null ) {
                
                BookInfoServicos obj = (BookInfoServicos) cbAdicionar.getSelectedItem();
                ftfPrecoUnitario.setText( String.valueOf( obj.PRECO ) );
                //System.out.println( "obj.PRECO "+obj.PRECO );
            }
                    
            
        }catch(Exception e) {
            JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Controle_De_Inserir, "
                    + "\ncbAdicionarActionPerformed(java.awt.event.ActionEvent evt)"
                    + e.getMessage()
                    + "\n", "cbAdicionarActionPerformed(java.awt.event.ActionEvent evt)" );
        }
    }//GEN-LAST:event_cbAdicionarActionPerformed

    private void tfObservacoesAdicionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfObservacoesAdicionaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfObservacoesAdicionaisActionPerformed

    private void btInserir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserir1ActionPerformed
        Controle_Inserir_Produto_Thread t1 = new Controle_Inserir_Produto_Thread( Home, OS, OS.OS_Corpo );

        t1.setName("Controle_Inserir_Produto_Thread");

        t1.start();
    }//GEN-LAST:event_btInserir1ActionPerformed

    private void cbInserirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbInserirProdutoActionPerformed
        try{
            //MeuObjeto obj = (MeuObjeto) combobox.getSelectedItem();
            if( cbInserirProduto.getSelectedItem() != null ) {
                
                BookInfoProdutos obj = (BookInfoProdutos) cbInserirProduto.getSelectedItem();
                ftfPrecoUnitarioProduto.setText( String.valueOf( obj.PRECODEVENDA ) );
                //System.out.println( "obj.PRECO "+obj.PRECO );
            }
            
        }catch(Exception e) {
            JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Controle_De_Inserir, "
                    + "\ncbAdicionarActionPerformed(java.awt.event.ActionEvent evt)"
                    + e.getMessage()
                    + "\n", "cbAdicionarActionPerformed(java.awt.event.ActionEvent evt)" );
        }
    }//GEN-LAST:event_cbInserirProdutoActionPerformed

    private void tfObservacoesAdicionaisProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfObservacoesAdicionaisProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfObservacoesAdicionaisProdutoActionPerformed

    private void tabOS_Corpo_Adicionar_ControleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabOS_Corpo_Adicionar_ControleMousePressed
        try{
            
            if( tabOS_Corpo_Adicionar_Controle.isEnabledAt( 0 )
                    && tabOS_Corpo_Adicionar_Controle.isEnabledAt( 1 ) ){
                
                int index = ( tabOS_Corpo_Adicionar_Controle.getSelectedIndex() );
        
                String nomeTabSelecionado = tabOS_Corpo_Adicionar_Controle.getTitleAt(index).trim();
        
                switch ( nomeTabSelecionado ) {
            
                    case "Adicionar serviço": 
                
                        OS.OS_Corpo.tabOSCorpo.setSelectedIndex( 0 );
                        
                    break;
                
                    case "Adicionar Produto": 
                
                        OS.OS_Corpo.tabOSCorpo.setSelectedIndex( 1 );
                        
                    break;    
            
                }
            }
        }catch(Exception e) {
            JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Controle_De_Inserir, "
                    + "\ntabOS_Corpo_Adicionar_ControleMousePressed(java.awt.event.MouseEvent evt))"
                    + e.getMessage()
                    + "\n", "tabOS_Corpo_Adicionar_ControleMousePressed(java.awt.event.MouseEvent evt)" );
        }
    }//GEN-LAST:event_tabOS_Corpo_Adicionar_ControleMousePressed

    private void ftfQuantidadeProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftfQuantidadeProdutoKeyPressed
    
        if( evt.getKeyCode() == KeyEvent.VK_ENTER )  {  
             
            Controle_Inserir_Produto_Thread t1 = new Controle_Inserir_Produto_Thread( Home, OS, OS.OS_Corpo );

            t1.setName("Controle_Inserir_Produto_Thread");

            t1.start();
            
        }
    }//GEN-LAST:event_ftfQuantidadeProdutoKeyPressed

    private void tfObservacoesAdicionaisProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfObservacoesAdicionaisProdutoKeyPressed
        if( evt.getKeyCode() == KeyEvent.VK_ENTER )  {  
             
            Controle_Inserir_Produto_Thread t1 = new Controle_Inserir_Produto_Thread( Home, OS, OS.OS_Corpo );

            t1.setName("Controle_Inserir_Produto_Thread");

            t1.start();
            
        }
    }//GEN-LAST:event_tfObservacoesAdicionaisProdutoKeyPressed

    private void ftfQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftfQuantidadeKeyPressed
        if( evt.getKeyCode() == KeyEvent.VK_ENTER )  {  
             
            Controle_Inserir_Servico_Thread t1 = new Controle_Inserir_Servico_Thread( Home, OS, OS.OS_Corpo );

            t1.setName("Controle_Inserir_Serviço_Thread");

            t1.start();
            
        }
    }//GEN-LAST:event_ftfQuantidadeKeyPressed

    private void tfObservacoesAdicionaisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfObservacoesAdicionaisKeyPressed
        if( evt.getKeyCode() == KeyEvent.VK_ENTER )  {  
             
            Controle_Inserir_Servico_Thread t1 = new Controle_Inserir_Servico_Thread( Home, OS, OS.OS_Corpo );

            t1.setName("Controle_Inserir_Serviço_Thread");

            t1.start();
            
        }
    }//GEN-LAST:event_tfObservacoesAdicionaisKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btInserir;
    public javax.swing.JButton btInserir1;
    public javax.swing.JComboBox cbAdicionar;
    public javax.swing.JComboBox cbInserirProduto;
    public javax.swing.JTextField ftfPrecoUnitario;
    public javax.swing.JTextField ftfPrecoUnitarioProduto;
    public javax.swing.JTextField ftfQuantidade;
    public javax.swing.JTextField ftfQuantidadeProduto;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbAdicionar;
    private javax.swing.JLabel lbAdicionar1;
    public javax.swing.JTabbedPane tabOS_Corpo_Adicionar_Controle;
    public javax.swing.JTextField tfObservacoesAdicionais;
    public javax.swing.JTextField tfObservacoesAdicionaisProduto;
    // End of variables declaration//GEN-END:variables
}
