/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package produto_;

import home.Home;
import java.awt.Color;
import produto__metodos.Controle_Thread_Produto;
import produto__metodos.CustoLucroVenda;
import produto__metodos.Setar_Categoria;
import produto__metodos.Setar_Unidade;
import utilidades.JOptionPaneMod;
import utilidades.RetornarNumeroInteiro;
import utilidades.ValidarNumeroFloat;

/**
 *
 * @author AnaMariana
 */
public class Produto extends javax.swing.JPanel {

    /**
     * Creates new form Cliente
     * @param Home2
     */
    public Produto( Home Home2 ) {
        initComponents();
        
        Home = Home2;
        
        cbUNIDADETRIBUTARIA.setBackground( new Color( 255, 255, 255 ) );
        cbCATEGORIA.setBackground( new Color( 255, 255, 255 ) );
        
        Setar_Unidade Setar_Unidade = new Setar_Unidade( Home, this );
        Setar_Categoria Setar_Categoria = new Setar_Categoria( Home, this );
    }
    
    Home Home;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfREFERENCIAEANGTIN = new javax.swing.JTextField();
        tfCODIGOPERSONALIZADO = new javax.swing.JTextField();
        tfPALAVRASCHAVE = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfPRECODECUSTO = new javax.swing.JTextField();
        tfVALORDELUCRO = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfEXCECAOTABELAIPI = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfESTOQUEMINIMO = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfNOME = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbUNIDADETRIBUTARIA = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        tfNCM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfPRECODEVENDA = new javax.swing.JTextField();
        cbCONTROLARESTOQUE = new javax.swing.JCheckBox();
        cbVENDERCOMESTOQUENEGATIVO = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taANOTACOESINTERNAS = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        cbCATEGORIA = new javax.swing.JComboBox();
        tfMARGEMDELUCRO = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfCODIGODEBARRAS = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tfLOCALIZACAOINTERNA = new javax.swing.JTextField();
        tfINFORMACOESADICIONAISPARANFE = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jpStatus1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Dados Produto");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Palavras-chave");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Preço de custo");

        tfREFERENCIAEANGTIN.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfREFERENCIAEANGTIN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfREFERENCIAEANGTIN.setPreferredSize(new java.awt.Dimension(212, 23));
        tfREFERENCIAEANGTIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfREFERENCIAEANGTINActionPerformed(evt);
            }
        });

        tfCODIGOPERSONALIZADO.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfCODIGOPERSONALIZADO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfCODIGOPERSONALIZADO.setPreferredSize(new java.awt.Dimension(212, 23));
        tfCODIGOPERSONALIZADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCODIGOPERSONALIZADOActionPerformed(evt);
            }
        });

        tfPALAVRASCHAVE.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfPALAVRASCHAVE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfPALAVRASCHAVE.setPreferredSize(new java.awt.Dimension(212, 23));
        tfPALAVRASCHAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPALAVRASCHAVEActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("NCM");

        tfPRECODECUSTO.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfPRECODECUSTO.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfPRECODECUSTO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfPRECODECUSTO.setPreferredSize(new java.awt.Dimension(212, 23));
        tfPRECODECUSTO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPRECODECUSTOFocusLost(evt);
            }
        });

        tfVALORDELUCRO.setEditable(false);
        tfVALORDELUCRO.setBackground(new java.awt.Color(255, 255, 255));
        tfVALORDELUCRO.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfVALORDELUCRO.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfVALORDELUCRO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfVALORDELUCRO.setPreferredSize(new java.awt.Dimension(212, 23));
        tfVALORDELUCRO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfVALORDELUCROFocusLost(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Exceção tabela IPI");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Unidade tributada ");

        tfEXCECAOTABELAIPI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfEXCECAOTABELAIPI.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfEXCECAOTABELAIPI.setPreferredSize(new java.awt.Dimension(212, 23));
        tfEXCECAOTABELAIPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEXCECAOTABELAIPIActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Preço de venda");

        tfESTOQUEMINIMO.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfESTOQUEMINIMO.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfESTOQUEMINIMO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfESTOQUEMINIMO.setPreferredSize(new java.awt.Dimension(212, 23));
        tfESTOQUEMINIMO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfESTOQUEMINIMOActionPerformed(evt);
            }
        });
        tfESTOQUEMINIMO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfESTOQUEMINIMOFocusLost(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Referência EAN/GTIN");

        tfNOME.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfNOME.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfNOME.setPreferredSize(new java.awt.Dimension(212, 23));
        tfNOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNOMEActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Nome ");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("Estoque mínimo");

        cbUNIDADETRIBUTARIA.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbUNIDADETRIBUTARIA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        cbUNIDADETRIBUTARIA.setPreferredSize(new java.awt.Dimension(212, 23));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Valor de Lucro");

        tfNCM.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfNCM.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfNCM.setPreferredSize(new java.awt.Dimension(212, 23));
        tfNCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNCMActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Categoria");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Código Personalizado");

        tfPRECODEVENDA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfPRECODEVENDA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfPRECODEVENDA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfPRECODEVENDA.setPreferredSize(new java.awt.Dimension(212, 23));
        tfPRECODEVENDA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPRECODEVENDAFocusLost(evt);
            }
        });

        cbCONTROLARESTOQUE.setBackground(new java.awt.Color(255, 255, 255));
        cbCONTROLARESTOQUE.setText("Controlar Estoque");

        cbVENDERCOMESTOQUENEGATIVO.setBackground(new java.awt.Color(255, 255, 255));
        cbVENDERCOMESTOQUENEGATIVO.setText("Vender com estoque negativo");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(135, 114));

        taANOTACOESINTERNAS.setColumns(9);
        taANOTACOESINTERNAS.setRows(2);
        taANOTACOESINTERNAS.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        jScrollPane1.setViewportView(taANOTACOESINTERNAS);

        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setText("Anotações Internas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cbCATEGORIA.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbCATEGORIA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        cbCATEGORIA.setPreferredSize(new java.awt.Dimension(212, 23));

        tfMARGEMDELUCRO.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfMARGEMDELUCRO.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfMARGEMDELUCRO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfMARGEMDELUCRO.setPreferredSize(new java.awt.Dimension(212, 23));
        tfMARGEMDELUCRO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfMARGEMDELUCROFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Margem de lucro %");

        tfCODIGODEBARRAS.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfCODIGODEBARRAS.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfCODIGODEBARRAS.setPreferredSize(new java.awt.Dimension(212, 23));
        tfCODIGODEBARRAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCODIGODEBARRASActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Inform. adicionais para a NFe");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("Localização interna");

        tfLOCALIZACAOINTERNA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfLOCALIZACAOINTERNA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfLOCALIZACAOINTERNA.setPreferredSize(new java.awt.Dimension(212, 23));
        tfLOCALIZACAOINTERNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLOCALIZACAOINTERNAActionPerformed(evt);
            }
        });

        tfINFORMACOESADICIONAISPARANFE.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfINFORMACOESADICIONAISPARANFE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfINFORMACOESADICIONAISPARANFE.setPreferredSize(new java.awt.Dimension(212, 23));
        tfINFORMACOESADICIONAISPARANFE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfINFORMACOESADICIONAISPARANFEActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("Código de barras");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbCATEGORIA, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfCODIGOPERSONALIZADO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbUNIDADETRIBUTARIA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbCONTROLARESTOQUE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfREFERENCIAEANGTIN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbVENDERCOMESTOQUENEGATIVO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tfESTOQUEMINIMO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfPALAVRASCHAVE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 2, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfNCM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(436, 436, 436)
                                .addComponent(tfEXCECAOTABELAIPI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(tfCODIGODEBARRAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfLOCALIZACAOINTERNA, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfINFORMACOESADICIONAISPARANFE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfPRECODECUSTO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfMARGEMDELUCRO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPRECODEVENDA, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfVALORDELUCRO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbCONTROLARESTOQUE, cbVENDERCOMESTOQUENEGATIVO, jLabel13, jLabel2, tfNCM, tfNOME, tfPRECODECUSTO, tfREFERENCIAEANGTIN});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(1, 1, 1)
                                .addComponent(cbCATEGORIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(2, 2, 2)
                                .addComponent(tfNOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(2, 2, 2)
                                .addComponent(tfPRECODEVENDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfVALORDELUCRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfMARGEMDELUCRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(24, 24, 24)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(1, 1, 1)
                                    .addComponent(tfPRECODECUSTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCODIGOPERSONALIZADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUNIDADETRIBUTARIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel14))
                                .addGap(2, 2, 2)
                                .addComponent(tfINFORMACOESADICIONAISPARANFE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfCODIGODEBARRAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfLOCALIZACAOINTERNA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(25, 25, 25)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(2, 2, 2)
                                .addComponent(tfNCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(2, 2, 2)
                                .addComponent(tfREFERENCIAEANGTIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(2, 2, 2)
                                .addComponent(tfEXCECAOTABELAIPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfESTOQUEMINIMO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfPALAVRASCHAVE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(cbCONTROLARESTOQUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbVENDERCOMESTOQUENEGATIVO))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbCATEGORIA, cbUNIDADETRIBUTARIA, tfCODIGOPERSONALIZADO, tfESTOQUEMINIMO, tfEXCECAOTABELAIPI, tfMARGEMDELUCRO, tfNCM, tfNOME, tfPALAVRASCHAVE, tfPRECODECUSTO, tfPRECODEVENDA, tfREFERENCIAEANGTIN, tfVALORDELUCRO});

        jpStatus1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(201, 239, 237)));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.gif"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setPreferredSize(new java.awt.Dimension(83, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.gif"))); // NOI18N
        jButton3.setText("Salvar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atualizar.png"))); // NOI18N
        jButton1.setText("Atualizar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jpStatus1Layout = new javax.swing.GroupLayout(jpStatus1);
        jpStatus1.setLayout(jpStatus1Layout);
        jpStatus1Layout.setHorizontalGroup(
            jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStatus1Layout.createSequentialGroup()
                .addContainerGap(576, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jpStatus1Layout.setVerticalGroup(
            jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpStatus1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpStatus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfNOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNOMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNOMEActionPerformed

    private void tfCODIGOPERSONALIZADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCODIGOPERSONALIZADOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCODIGOPERSONALIZADOActionPerformed

    private void tfNCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNCMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNCMActionPerformed

    private void tfREFERENCIAEANGTINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfREFERENCIAEANGTINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfREFERENCIAEANGTINActionPerformed

    private void tfEXCECAOTABELAIPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEXCECAOTABELAIPIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEXCECAOTABELAIPIActionPerformed

    private void tfESTOQUEMINIMOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfESTOQUEMINIMOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfESTOQUEMINIMOActionPerformed

    private void tfPALAVRASCHAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPALAVRASCHAVEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPALAVRASCHAVEActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Home.ControleTabs.removerTabSelecionado();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if( !tfNOME.getText().trim().equals("") ) {

            Controle_Thread_Produto t1 = new Controle_Thread_Produto( Home, this );
            t1.setName("Controle Thread Contato");
            t1.start();
        }
        else{
            JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "O Campo Nome não pode ser nulo", "Nome do Produto" );
            tfNOME.requestFocus();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        Setar_Unidade Setar_Unidade = new Setar_Unidade( Home, this );
        Setar_Categoria Setar_Categoria = new Setar_Categoria( Home, this );
    }//GEN-LAST:event_jButton1MousePressed

    private void tfMARGEMDELUCROFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfMARGEMDELUCROFocusLost
        if ( ValidarNumeroFloat.floatTF( tfMARGEMDELUCRO, tfMARGEMDELUCRO.getText().trim(), "Margem de lucro", true ) == true ){
            CustoLucroVenda CustoLucroVenda = new CustoLucroVenda( this, "Margem de lucro" );
        }
    }//GEN-LAST:event_tfMARGEMDELUCROFocusLost

    private void tfPRECODECUSTOFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPRECODECUSTOFocusLost
        if ( ValidarNumeroFloat.floatTF( tfPRECODECUSTO, tfPRECODECUSTO.getText().trim(), "Preço de Custo", true ) == true ){
            CustoLucroVenda CustoLucroVenda = new CustoLucroVenda( this, "Preço de Custo" );
        }
    }//GEN-LAST:event_tfPRECODECUSTOFocusLost

    private void tfPRECODEVENDAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPRECODEVENDAFocusLost
        if ( ValidarNumeroFloat.floatTF( tfPRECODEVENDA, tfPRECODEVENDA.getText().trim(), "Preço de Venda", true ) == true ){
            CustoLucroVenda CustoLucroVenda = new CustoLucroVenda( this, "Preço de Venda" );
        }
    }//GEN-LAST:event_tfPRECODEVENDAFocusLost

    private void tfESTOQUEMINIMOFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfESTOQUEMINIMOFocusLost
        RetornarNumeroInteiro.intTF( tfESTOQUEMINIMO, tfESTOQUEMINIMO.getText().trim(), "Estoque mínimo", true );
    }//GEN-LAST:event_tfESTOQUEMINIMOFocusLost

    private void tfCODIGODEBARRASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCODIGODEBARRASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCODIGODEBARRASActionPerformed

    private void tfLOCALIZACAOINTERNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLOCALIZACAOINTERNAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLOCALIZACAOINTERNAActionPerformed

    private void tfINFORMACOESADICIONAISPARANFEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfINFORMACOESADICIONAISPARANFEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfINFORMACOESADICIONAISPARANFEActionPerformed

    private void tfVALORDELUCROFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfVALORDELUCROFocusLost
        ValidarNumeroFloat.floatTF( tfVALORDELUCRO, tfVALORDELUCRO.getText().trim(), "Valor de lucro", true );
    }//GEN-LAST:event_tfVALORDELUCROFocusLost

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox cbCATEGORIA;
    public javax.swing.JCheckBox cbCONTROLARESTOQUE;
    public javax.swing.JComboBox cbUNIDADETRIBUTARIA;
    public javax.swing.JCheckBox cbVENDERCOMESTOQUENEGATIVO;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpStatus1;
    public javax.swing.JTextArea taANOTACOESINTERNAS;
    public javax.swing.JTextField tfCODIGODEBARRAS;
    public javax.swing.JTextField tfCODIGOPERSONALIZADO;
    public javax.swing.JTextField tfESTOQUEMINIMO;
    public javax.swing.JTextField tfEXCECAOTABELAIPI;
    public javax.swing.JTextField tfINFORMACOESADICIONAISPARANFE;
    public javax.swing.JTextField tfLOCALIZACAOINTERNA;
    public javax.swing.JTextField tfMARGEMDELUCRO;
    public javax.swing.JTextField tfNCM;
    public javax.swing.JTextField tfNOME;
    public javax.swing.JTextField tfPALAVRASCHAVE;
    public javax.swing.JTextField tfPRECODECUSTO;
    public javax.swing.JTextField tfPRECODEVENDA;
    public javax.swing.JTextField tfREFERENCIAEANGTIN;
    public javax.swing.JTextField tfVALORDELUCRO;
    // End of variables declaration//GEN-END:variables
             
}
