/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package home;

import home_controle.AbrirTabInicial;
import home_controle.ControleTabs;
import home_incluir.Incluir_Contas_Disponiveis;
import home_incluir.Incluir_Grupo_Contato;
import home_incluir.Incluir_Servico;
import home_incluir.Incluir_Tipo_de_Usuario;
import home_incluir.Incluir_Contato;
import home_incluir.Incluir_Formas_de_Pagamento;
import home_incluir.Incluir_OS;
import home_incluir.Incluir_Produto;
import home_incluir.Incluir_Produto_Categoria;
import home_incluir.Incluir_Tipos_de_Documento;
import home_incluir.Incluir_Unidade;
import home_incluir.Incluir_Usuario;
import utilidades.Icone_Do_Programa;

/**
 *
 * @author ana
 */
public class Home extends javax.swing.JFrame {

    public ControleTabs ControleTabs = new ControleTabs( this );
    public AbrirTabInicial AbrirTabInicial = new AbrirTabInicial( this );
    
    /**
     * Creates new form Home
     * @param ip2
     */
    public Home( String ip2 ) { 
        Icone_Do_Programa Icone_Do_Programa = new Icone_Do_Programa(this);
        ip = ip2;
        
        initComponents();
        AbrirTabInicial.inicio();
        //tabHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    }
    
    public String ip;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Barra_de_Titulo = new javax.swing.JPanel();
        tabHome = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem67 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem47 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem50 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem56 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem62 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem79 = new javax.swing.JMenuItem();
        jMenuItem80 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenuItem70 = new javax.swing.JMenuItem();
        jMenuItem71 = new javax.swing.JMenuItem();
        jMenuItem72 = new javax.swing.JMenuItem();
        jMenu29 = new javax.swing.JMenu();
        jMenuItem73 = new javax.swing.JMenuItem();
        jMenuItem74 = new javax.swing.JMenuItem();
        jMenuItem75 = new javax.swing.JMenuItem();
        jMenu30 = new javax.swing.JMenu();
        jMenuItem76 = new javax.swing.JMenuItem();
        jMenuItem77 = new javax.swing.JMenuItem();
        jMenuItem78 = new javax.swing.JMenuItem();
        jMenu24 = new javax.swing.JMenu();
        jMenuItem53 = new javax.swing.JMenuItem();
        jMenuItem54 = new javax.swing.JMenuItem();
        jMenuItem55 = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu21 = new javax.swing.JMenu();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenuItem43 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem65 = new javax.swing.JMenuItem();
        jMenuItem66 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem13 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout Barra_de_TituloLayout = new javax.swing.GroupLayout(Barra_de_Titulo);
        Barra_de_Titulo.setLayout(Barra_de_TituloLayout);
        Barra_de_TituloLayout.setHorizontalGroup(
            Barra_de_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 916, Short.MAX_VALUE)
        );
        Barra_de_TituloLayout.setVerticalGroup(
            Barra_de_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );

        tabHome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jMenu1.setText("Arquivo");
        jMenuBar1.add(jMenu1);

        jMenu8.setText("Editar");
        jMenuBar1.add(jMenu8);

        jMenu3.setText("Cadastros");

        jMenuItem67.setText("Grupo");
        jMenuItem67.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem67MousePressed(evt);
            }
        });
        jMenu3.add(jMenuItem67);

        jMenuItem38.setText("Clientes");
        jMenuItem38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem38MousePressed(evt);
            }
        });
        jMenu3.add(jMenuItem38);

        jMenuItem35.setText("Fornecedores");
        jMenuItem35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem35MousePressed(evt);
            }
        });
        jMenu3.add(jMenuItem35);

        jMenuItem32.setText("Transportadores");
        jMenuItem32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem32MousePressed(evt);
            }
        });
        jMenu3.add(jMenuItem32);
        jMenu3.add(jSeparator4);

        jMenuItem47.setText("Unidades");
        jMenuItem47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem47MousePressed(evt);
            }
        });
        jMenu3.add(jMenuItem47);

        jMenuItem20.setText("Categoria");
        jMenuItem20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem20MousePressed(evt);
            }
        });
        jMenu3.add(jMenuItem20);

        jMenuItem50.setText("Produtos");
        jMenuItem50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem50MousePressed(evt);
            }
        });
        jMenu3.add(jMenuItem50);
        jMenu3.add(jSeparator5);

        jMenuItem56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/servicos.png"))); // NOI18N
        jMenuItem56.setText("Serviços");
        jMenuItem56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem56MousePressed(evt);
            }
        });
        jMenuItem56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem56ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem56);
        jMenu3.add(jSeparator1);

        jMenuItem26.setText("Funções");
        jMenuItem26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem26MousePressed(evt);
            }
        });
        jMenu3.add(jMenuItem26);

        jMenuItem23.setText("Departamentos");
        jMenuItem23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem23MousePressed(evt);
            }
        });
        jMenu3.add(jMenuItem23);

        jMenuItem62.setText("Funcionários");
        jMenuItem62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem62MousePressed(evt);
            }
        });
        jMenu3.add(jMenuItem62);
        jMenu3.add(jSeparator6);

        jMenuItem79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tipodeusuario.gif"))); // NOI18N
        jMenuItem79.setText("Tipo de Usuário");
        jMenuItem79.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem79MousePressed(evt);
            }
        });
        jMenu3.add(jMenuItem79);

        jMenuItem80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jMenuItem80.setText("Usuários do Sistema");
        jMenuItem80.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem80MousePressed(evt);
            }
        });
        jMenu3.add(jMenuItem80);

        jMenuBar1.add(jMenu3);

        jMenu10.setText("Veículos");

        jMenu17.setText("Modelos");

        jMenuItem70.setText("Incluir");
        jMenuItem70.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem70MousePressed(evt);
            }
        });
        jMenu17.add(jMenuItem70);

        jMenuItem71.setText("Alterar");
        jMenu17.add(jMenuItem71);

        jMenuItem72.setText("Excluir");
        jMenu17.add(jMenuItem72);

        jMenu10.add(jMenu17);

        jMenu29.setText("Fabricantes");

        jMenuItem73.setText("Incluir");
        jMenuItem73.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem73MousePressed(evt);
            }
        });
        jMenu29.add(jMenuItem73);

        jMenuItem74.setText("Alterar");
        jMenu29.add(jMenuItem74);

        jMenuItem75.setText("Excluir");
        jMenu29.add(jMenuItem75);

        jMenu10.add(jMenu29);

        jMenu30.setText("Troca de Óleo");

        jMenuItem76.setText("Incluir");
        jMenuItem76.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem76MousePressed(evt);
            }
        });
        jMenu30.add(jMenuItem76);

        jMenuItem77.setText("Alterar");
        jMenu30.add(jMenuItem77);

        jMenuItem78.setText("Excluir");
        jMenu30.add(jMenuItem78);

        jMenu10.add(jMenu30);

        jMenu24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/veiculo.png"))); // NOI18N
        jMenu24.setText("Veiculos");

        jMenuItem53.setText("Incluir");
        jMenuItem53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem53MousePressed(evt);
            }
        });
        jMenu24.add(jMenuItem53);

        jMenuItem54.setText("Alterar");
        jMenu24.add(jMenuItem54);

        jMenuItem55.setText("Excluir");
        jMenu24.add(jMenuItem55);

        jMenu10.add(jMenu24);

        jMenu16.setText("Agendamentos");

        jMenuItem29.setText("Incluir");
        jMenuItem29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem29MousePressed(evt);
            }
        });
        jMenu16.add(jMenuItem29);

        jMenuItem30.setText("Alterar");
        jMenu16.add(jMenuItem30);

        jMenuItem31.setText("Excluir");
        jMenu16.add(jMenuItem31);

        jMenu10.add(jMenu16);

        jMenuBar1.add(jMenu10);

        jMenu4.setText("Operações");

        jMenu21.setText("Entrar Mercadorias");

        jMenuItem41.setText("Incluir");
        jMenuItem41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem41MousePressed(evt);
            }
        });
        jMenu21.add(jMenuItem41);

        jMenuItem42.setText("Alterar");
        jMenu21.add(jMenuItem42);

        jMenuItem43.setText("Excluir");
        jMenu21.add(jMenuItem43);

        jMenu4.add(jMenu21);
        jMenu4.add(jSeparator3);

        jMenuItem44.setText("Ordens de Serviço");
        jMenuItem44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem44MousePressed(evt);
            }
        });
        jMenu4.add(jMenuItem44);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Financeiro");

        jMenuItem65.setText("Contas a pagar");
        jMenuItem65.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem65MousePressed(evt);
            }
        });
        jMenu5.add(jMenuItem65);

        jMenuItem66.setText("Contas a receber");
        jMenu5.add(jMenuItem66);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Acessórios");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Impressões");
        jMenuBar1.add(jMenu7);

        jMenu9.setText("Configurações");

        jMenuItem8.setText("Contas disponíveis");
        jMenuItem8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem8MousePressed(evt);
            }
        });
        jMenu9.add(jMenuItem8);

        jMenuItem11.setText("Tipos de documento");
        jMenuItem11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem11MousePressed(evt);
            }
        });
        jMenu9.add(jMenuItem11);

        jMenuItem12.setText("Formas de pagamento");
        jMenuItem12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem12MousePressed(evt);
            }
        });
        jMenu9.add(jMenuItem12);
        jMenu9.add(jSeparator2);

        jMenuItem13.setText("Configurações gerais");
        jMenu9.add(jMenuItem13);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Barra_de_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabHome)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Barra_de_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tabHome, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem20MousePressed
       Incluir_Produto_Categoria Incluir_Categoria = new Incluir_Produto_Categoria( this );
    }//GEN-LAST:event_jMenuItem20MousePressed

    private void jMenuItem32MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem32MousePressed
        Incluir_Contato Incluir_Transportador = new Incluir_Contato( this, "Transportador" );
    }//GEN-LAST:event_jMenuItem32MousePressed

    private void jMenuItem35MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem35MousePressed
        Incluir_Contato Incluir_Transportador = new Incluir_Contato( this, "Fornecedor" );
    }//GEN-LAST:event_jMenuItem35MousePressed

    private void jMenuItem38MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem38MousePressed
        Incluir_Contato Incluir_Transportador = new Incluir_Contato( this, "Cliente" );
    }//GEN-LAST:event_jMenuItem38MousePressed

    private void jMenuItem41MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem41MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem41MousePressed

    private void jMenuItem44MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem44MousePressed
        Incluir_OS Incluir_OS = new Incluir_OS( this );
    }//GEN-LAST:event_jMenuItem44MousePressed

    private void jMenuItem47MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem47MousePressed
        Incluir_Unidade Incluir_Unidade = new Incluir_Unidade( this );
    }//GEN-LAST:event_jMenuItem47MousePressed

    private void jMenuItem50MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem50MousePressed
        Incluir_Produto Incluir_Produto = new Incluir_Produto( this );
    }//GEN-LAST:event_jMenuItem50MousePressed

    private void jMenuItem53MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem53MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem53MousePressed

    private void jMenuItem23MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem23MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem23MousePressed

    private void jMenuItem62MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem62MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem62MousePressed

    private void jMenuItem65MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem65MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem65MousePressed

    private void jMenuItem67MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem67MousePressed
        Incluir_Grupo_Contato Incluir_Grupo_Contato = new Incluir_Grupo_Contato( this );
    }//GEN-LAST:event_jMenuItem67MousePressed

    private void jMenuItem26MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem26MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem26MousePressed

    private void jMenuItem29MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem29MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem29MousePressed

    private void jMenuItem70MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem70MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem70MousePressed

    private void jMenuItem73MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem73MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem73MousePressed

    private void jMenuItem76MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem76MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem76MousePressed

    private void jMenuItem79MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem79MousePressed
        Incluir_Tipo_de_Usuario Incluir_Tipo_de_Usuario = new Incluir_Tipo_de_Usuario( this );
    }//GEN-LAST:event_jMenuItem79MousePressed

    private void jMenuItem80MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem80MousePressed
        Incluir_Usuario Incluir_Usuario = new Incluir_Usuario( this );
    }//GEN-LAST:event_jMenuItem80MousePressed

    private void jMenuItem56MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem56MousePressed
        Incluir_Servico Incluir_Servico = new Incluir_Servico( this );
    }//GEN-LAST:event_jMenuItem56MousePressed

    private void jMenuItem56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem56ActionPerformed

    private void jMenuItem11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem11MousePressed
        Incluir_Tipos_de_Documento Incluir_Tipos_de_Documento = new Incluir_Tipos_de_Documento( this );
    }//GEN-LAST:event_jMenuItem11MousePressed

    private void jMenuItem8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem8MousePressed
        Incluir_Contas_Disponiveis Incluir_Contas_Disponiveis = new Incluir_Contas_Disponiveis( this );
    }//GEN-LAST:event_jMenuItem8MousePressed

    private void jMenuItem12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem12MousePressed
        Incluir_Formas_de_Pagamento Incluir_Formas_de_Pagamento = new Incluir_Formas_de_Pagamento( this );
    }//GEN-LAST:event_jMenuItem12MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home( "localhost" ).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Barra_de_Titulo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu30;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem47;
    private javax.swing.JMenuItem jMenuItem50;
    private javax.swing.JMenuItem jMenuItem53;
    private javax.swing.JMenuItem jMenuItem54;
    private javax.swing.JMenuItem jMenuItem55;
    private javax.swing.JMenuItem jMenuItem56;
    private javax.swing.JMenuItem jMenuItem62;
    private javax.swing.JMenuItem jMenuItem65;
    private javax.swing.JMenuItem jMenuItem66;
    private javax.swing.JMenuItem jMenuItem67;
    private javax.swing.JMenuItem jMenuItem70;
    private javax.swing.JMenuItem jMenuItem71;
    private javax.swing.JMenuItem jMenuItem72;
    private javax.swing.JMenuItem jMenuItem73;
    private javax.swing.JMenuItem jMenuItem74;
    private javax.swing.JMenuItem jMenuItem75;
    private javax.swing.JMenuItem jMenuItem76;
    private javax.swing.JMenuItem jMenuItem77;
    private javax.swing.JMenuItem jMenuItem78;
    private javax.swing.JMenuItem jMenuItem79;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem80;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    public javax.swing.JTabbedPane tabHome;
    // End of variables declaration//GEN-END:variables
}
