/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package OS_Adicionar_Produto_Servico;

/**
 *
 * @author ana
 */
public class Preenchimento_Lista extends javax.swing.JPanel {

    /**
     * Creates new form Preenchimento_da_Lista
     * @param codigo2
     * @param nomeProduto2
     * @param unidade2
     * @param valorUnitario2
     * @param quantidade2
     * @param observacao2
     */
    public Preenchimento_Lista( int codigo2, String nomeProduto2, String unidade2, float valorUnitario2, float quantidade2, String observacao2 ) {
        initComponents();
             
        codigo               = codigo2;
        nomeProduto          = nomeProduto2;
        unidade              = unidade2;
        valorUnitario        = valorUnitario2;
        quantidade           = quantidade2;
        observacao           = observacao2;
        
        vUnitXQuant = valorUnitario2 * quantidade2;
    }
    
    public int codigo                ;
    public String nomeProduto    = "";
    public String unidade        = "";
    public float valorUnitario       ;
    public float quantidade          ;
    public String observacao     = "";
    public float vUnitXQuant         ;
    
    java.awt.Color amarelo = new java.awt.Color( 255,255,204 );
    java.awt.Color branco = new java.awt.Color( 255,255,255 );
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNomeProduto = new javax.swing.JLabel();
        lbObservacao = new javax.swing.JLabel();
        lbRemover = new javax.swing.JLabel();
        Unidade = new javax.swing.JLabel();
        lbCodigo3 = new javax.swing.JLabel();
        lbValorUnitario = new javax.swing.JLabel();
        lbQuantidade = new javax.swing.JLabel();
        lbValorUnitXQuantidade = new javax.swing.JLabel();
        lbCodigo7 = new javax.swing.JLabel();
        lbUnidade = new javax.swing.JLabel();
        lbCodigo4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(467, 68));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        lbNomeProduto.setBackground(new java.awt.Color(255, 255, 255));
        lbNomeProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbNomeProduto.setText("Produto 1");
        lbNomeProduto.setToolTipText("");
        lbNomeProduto.setPreferredSize(new java.awt.Dimension(63, 19));
        lbNomeProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbNomeProdutoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbNomeProdutoMouseExited(evt);
            }
        });

        lbObservacao.setBackground(new java.awt.Color(255, 255, 255));
        lbObservacao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbObservacao.setForeground(new java.awt.Color(102, 102, 102));
        lbObservacao.setText("Observação");
        lbObservacao.setToolTipText("");
        lbObservacao.setPreferredSize(new java.awt.Dimension(63, 19));
        lbObservacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbObservacaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbObservacaoMouseExited(evt);
            }
        });

        lbRemover.setBackground(new java.awt.Color(255, 255, 255));
        lbRemover.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lixo.jpg"))); // NOI18N
        lbRemover.setToolTipText("Excluir Ítem");
        lbRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbRemoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbRemoverMouseExited(evt);
            }
        });

        Unidade.setBackground(new java.awt.Color(255, 255, 255));
        Unidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Unidade.setForeground(new java.awt.Color(102, 102, 102));
        Unidade.setText("Unidade");
        Unidade.setToolTipText("");
        Unidade.setPreferredSize(new java.awt.Dimension(31, 19));
        Unidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UnidadeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UnidadeMouseExited(evt);
            }
        });

        lbCodigo3.setBackground(new java.awt.Color(255, 255, 255));
        lbCodigo3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbCodigo3.setForeground(new java.awt.Color(102, 102, 102));
        lbCodigo3.setText("Quant:");
        lbCodigo3.setToolTipText("");
        lbCodigo3.setPreferredSize(new java.awt.Dimension(31, 19));
        lbCodigo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbCodigo3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbCodigo3MouseExited(evt);
            }
        });

        lbValorUnitario.setBackground(new java.awt.Color(255, 255, 255));
        lbValorUnitario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbValorUnitario.setForeground(new java.awt.Color(102, 102, 102));
        lbValorUnitario.setText("19,00");
        lbValorUnitario.setToolTipText("");
        lbValorUnitario.setPreferredSize(new java.awt.Dimension(31, 19));
        lbValorUnitario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbValorUnitarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbValorUnitarioMouseExited(evt);
            }
        });

        lbQuantidade.setBackground(new java.awt.Color(255, 255, 255));
        lbQuantidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbQuantidade.setForeground(new java.awt.Color(102, 102, 102));
        lbQuantidade.setText("1");
        lbQuantidade.setToolTipText("");
        lbQuantidade.setPreferredSize(new java.awt.Dimension(31, 19));
        lbQuantidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbQuantidadeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbQuantidadeMouseExited(evt);
            }
        });

        lbValorUnitXQuantidade.setBackground(new java.awt.Color(255, 255, 255));
        lbValorUnitXQuantidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbValorUnitXQuantidade.setText("19,00");
        lbValorUnitXQuantidade.setToolTipText("");
        lbValorUnitXQuantidade.setPreferredSize(new java.awt.Dimension(31, 19));
        lbValorUnitXQuantidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbValorUnitXQuantidadeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbValorUnitXQuantidadeMouseExited(evt);
            }
        });

        lbCodigo7.setBackground(new java.awt.Color(255, 255, 255));
        lbCodigo7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbCodigo7.setText("R$ ");
        lbCodigo7.setToolTipText("");
        lbCodigo7.setPreferredSize(new java.awt.Dimension(31, 19));
        lbCodigo7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbCodigo7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbCodigo7MouseExited(evt);
            }
        });

        lbUnidade.setBackground(new java.awt.Color(255, 255, 255));
        lbUnidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbUnidade.setForeground(new java.awt.Color(102, 102, 102));
        lbUnidade.setText("CX");
        lbUnidade.setToolTipText("");
        lbUnidade.setPreferredSize(new java.awt.Dimension(31, 19));
        lbUnidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbUnidadeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbUnidadeMouseExited(evt);
            }
        });

        lbCodigo4.setBackground(new java.awt.Color(255, 255, 255));
        lbCodigo4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbCodigo4.setForeground(new java.awt.Color(102, 102, 102));
        lbCodigo4.setText("V. Unit: R$");
        lbCodigo4.setToolTipText("");
        lbCodigo4.setPreferredSize(new java.awt.Dimension(31, 19));
        lbCodigo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbCodigo4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbCodigo4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(lbCodigo7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbValorUnitXQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Unidade, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(lbQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbNomeProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Unidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbValorUnitXQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbCodigo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbNomeProduto, lbObservacao});

    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        this.setBackground( amarelo );
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.setBackground( branco );
    }//GEN-LAST:event_formMouseExited

    private void lbNomeProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNomeProdutoMouseEntered
        this.setBackground( amarelo );
    }//GEN-LAST:event_lbNomeProdutoMouseEntered

    private void lbNomeProdutoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNomeProdutoMouseExited
        this.setBackground( branco );
    }//GEN-LAST:event_lbNomeProdutoMouseExited

    private void lbObservacaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbObservacaoMouseEntered
        this.setBackground( amarelo );
    }//GEN-LAST:event_lbObservacaoMouseEntered

    private void lbObservacaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbObservacaoMouseExited
        this.setBackground( branco );
    }//GEN-LAST:event_lbObservacaoMouseExited

    private void UnidadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UnidadeMouseEntered
        this.setBackground( amarelo );
    }//GEN-LAST:event_UnidadeMouseEntered

    private void UnidadeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UnidadeMouseExited
        this.setBackground( branco );
    }//GEN-LAST:event_UnidadeMouseExited

    private void lbCodigo3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCodigo3MouseEntered
        this.setBackground( amarelo );
    }//GEN-LAST:event_lbCodigo3MouseEntered

    private void lbCodigo3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCodigo3MouseExited
        this.setBackground( branco );
    }//GEN-LAST:event_lbCodigo3MouseExited

    private void lbValorUnitarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbValorUnitarioMouseEntered
        this.setBackground( amarelo );
    }//GEN-LAST:event_lbValorUnitarioMouseEntered

    private void lbValorUnitarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbValorUnitarioMouseExited
         this.setBackground( branco );
    }//GEN-LAST:event_lbValorUnitarioMouseExited

    private void lbQuantidadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbQuantidadeMouseEntered
        this.setBackground( amarelo );
    }//GEN-LAST:event_lbQuantidadeMouseEntered

    private void lbQuantidadeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbQuantidadeMouseExited
        this.setBackground( branco );
    }//GEN-LAST:event_lbQuantidadeMouseExited

    private void lbValorUnitXQuantidadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbValorUnitXQuantidadeMouseEntered
       this.setBackground( amarelo );
    }//GEN-LAST:event_lbValorUnitXQuantidadeMouseEntered

    private void lbValorUnitXQuantidadeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbValorUnitXQuantidadeMouseExited
        this.setBackground( branco );
    }//GEN-LAST:event_lbValorUnitXQuantidadeMouseExited

    private void lbCodigo7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCodigo7MouseEntered
        this.setBackground( amarelo );
    }//GEN-LAST:event_lbCodigo7MouseEntered

    private void lbCodigo7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCodigo7MouseExited
        this.setBackground( branco );
    }//GEN-LAST:event_lbCodigo7MouseExited

    private void lbUnidadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUnidadeMouseEntered
        this.setBackground( amarelo );
    }//GEN-LAST:event_lbUnidadeMouseEntered

    private void lbUnidadeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUnidadeMouseExited
        this.setBackground( branco );
    }//GEN-LAST:event_lbUnidadeMouseExited

    private void lbCodigo4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCodigo4MouseEntered
        this.setBackground( amarelo );
    }//GEN-LAST:event_lbCodigo4MouseEntered

    private void lbCodigo4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCodigo4MouseExited
        this.setBackground( branco );
    }//GEN-LAST:event_lbCodigo4MouseExited

    private void lbRemoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRemoverMouseEntered
        this.setBackground( amarelo );
        
        lbRemover.setToolTipText(
                        "Exluir: "+nomeProduto
                        + " R$: " + vUnitXQuant
                );
    }//GEN-LAST:event_lbRemoverMouseEntered

    private void lbRemoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRemoverMouseExited
        this.setBackground( branco );
    }//GEN-LAST:event_lbRemoverMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Unidade;
    public javax.swing.JLabel lbCodigo3;
    public javax.swing.JLabel lbCodigo4;
    public javax.swing.JLabel lbCodigo7;
    public javax.swing.JLabel lbNomeProduto;
    public javax.swing.JLabel lbObservacao;
    public javax.swing.JLabel lbQuantidade;
    public javax.swing.JLabel lbRemover;
    public javax.swing.JLabel lbUnidade;
    public javax.swing.JLabel lbValorUnitXQuantidade;
    public javax.swing.JLabel lbValorUnitario;
    // End of variables declaration//GEN-END:variables
}
