/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formas_de_pagamento;

import home.Home;

/**
 *
 * @author AnaMariana
 */
public class Formas_de_Pagamento_Home extends javax.swing.JPanel {
    
    Home Home;              
    Formas_de_Pagamento_Home_Inicio Formas_de_Pagamento_Home_Inicio;
    
    public Formas_de_Pagamento Formas_de_Pagamento;
    public Formas_de_Pagamento_Botoes Formas_de_Pagamento_Botoes;
    
    //public List<BookInfoContaDeDestino> listBookInfoContaDeDestino = new ArrayList();

    /**
     * Creates new form Cliente
     * @param Home2
     */
    public Formas_de_Pagamento_Home( Home Home2 ) {
        Home = Home2;
        
        initComponents();
       
        Formas_de_Pagamento_Home_Inicio = new Formas_de_Pagamento_Home_Inicio( Home, this);
        
        Formas_de_Pagamento_Home_Inicio.inicio();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
             
}
