/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package contato;

import contato_metodos.Controle_Thread_Contato;
import contato_metodos.Setar_Grupo;
import eventos.Eventos_Clientes_CB_Estados;
import home.Home;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFormattedTextField;
import javax.swing.text.MaskFormatter;
import utilidades.JOptionPaneMod;

/**
 *
 * @author AnaMariana
 */
public class Contato extends javax.swing.JPanel {

    /**
     * Creates new form Cliente
     * @param Home2
     * @param tipoContato2
     */
    public Contato( Home Home2, String tipoContato2 ) {
        initComponents();
        setarComboBox("pais");
        setarComboBox("brasil_estados");
        setarComboBox( "brasil_ceara_cidades" );
        
        setarEventosComboBoxs();
        
        Home        = Home2;
        tipoContato = tipoContato2;
        
        Inicio_Contato Inicio_Contato = new Inicio_Contato( this, tipoContato );
        
        Setar_Grupo Setar_Grupo = new Setar_Grupo( Home, this );

    }
    
    Home Home;
    String tipoContato;
    
    private void setarComboBox(String st){ 
        switch(st){
            case "pais": setarComboBoxPais( "pais" ); break;
            case "brasil_estados": setarComboBoxEstado( "brasil_estados" ); break;  
            case "brasil_ceara_cidades": setarComboBoxCidade( "brasil_ceara_cidades" ); break;    
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cbTipoFornecedor = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAnotacoesGerais = new javax.swing.JTextArea();
        cbTipoCliente = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        cbTipoTransportador = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tfPalavrasChave = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfComplemento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfInscrEstaSubstTrib = new javax.swing.JTextField();
        tfInscricaoEstadual = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tfInscricaoSuframa = new javax.swing.JTextField();
        tfBairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tfOutroEmail = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tfNumero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbPais = new javax.swing.JComboBox();
        tfNomeFantasia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfEndereco = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfFacebook = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tfInscricaoMunicipal = new javax.swing.JTextField();
        cbCidade = new javax.swing.JComboBox();
        cbEstado = new javax.swing.JComboBox();
        tfNomeResponsavel = new javax.swing.JTextField();
        tfDataNascimento = new javax.swing.JFormattedTextField();
        tfFone2Fax = new javax.swing.JFormattedTextField();
        tfFone3Celular = new javax.swing.JFormattedTextField();
        tfTelefone = new javax.swing.JFormattedTextField();
        tfCPFOuCNPJ = new javax.swing.JFormattedTextField();
        tfCEP = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        rbPessoaJuridica = new javax.swing.JRadioButton();
        rbPessoaFisica = new javax.swing.JRadioButton();
        cbGrupo = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        jpStatus = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Dados básicos");

        cbTipoFornecedor.setText("Fornecedor");
        cbTipoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoFornecedorActionPerformed(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(135, 114));

        taAnotacoesGerais.setColumns(9);
        taAnotacoesGerais.setRows(5);
        taAnotacoesGerais.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        jScrollPane1.setViewportView(taAnotacoesGerais);

        cbTipoCliente.setText("Cliente");
        cbTipoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoClienteActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setText("Tipo de Contato");

        cbTipoTransportador.setText("Transportador");
        cbTipoTransportador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoTransportadorActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setText("Anotações Gerais");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbTipoCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbTipoFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbTipoTransportador, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbTipoCliente)
                .addGap(7, 7, 7)
                .addComponent(cbTipoFornecedor)
                .addGap(7, 7, 7)
                .addComponent(cbTipoTransportador)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tfPalavrasChave.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfPalavrasChave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfPalavrasChave.setPreferredSize(new java.awt.Dimension(185, 23));
        tfPalavrasChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPalavrasChaveActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Cidade");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Inscr Est Subst Trib");

        tfComplemento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfComplemento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfComplemento.setPreferredSize(new java.awt.Dimension(185, 23));
        tfComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfComplementoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Endereço");

        tfInscrEstaSubstTrib.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfInscrEstaSubstTrib.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfInscrEstaSubstTrib.setPreferredSize(new java.awt.Dimension(185, 23));
        tfInscrEstaSubstTrib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInscrEstaSubstTribActionPerformed(evt);
            }
        });

        tfInscricaoEstadual.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfInscricaoEstadual.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfInscricaoEstadual.setPreferredSize(new java.awt.Dimension(185, 23));
        tfInscricaoEstadual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInscricaoEstadualActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setText("E-mail");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setText("Fone 2 (fax)");

        tfInscricaoSuframa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfInscricaoSuframa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfInscricaoSuframa.setPreferredSize(new java.awt.Dimension(185, 23));
        tfInscricaoSuframa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInscricaoSuframaActionPerformed(evt);
            }
        });

        tfBairro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfBairro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfBairro.setPreferredSize(new java.awt.Dimension(185, 23));
        tfBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBairroActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Número");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Nome do responsável");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("Bairro");

        tfOutroEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfOutroEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfOutroEmail.setPreferredSize(new java.awt.Dimension(185, 23));
        tfOutroEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfOutroEmailActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setText("Palavras-chave");

        tfNumero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfNumero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfNumero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfNumero.setPreferredSize(new java.awt.Dimension(185, 23));
        tfNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumeroActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Inscrição Municipal");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("CEP (procurar)");

        tfNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfNome.setPreferredSize(new java.awt.Dimension(185, 23));
        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Nome ou Razão social");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("Estado");

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setText("Facebook");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Inscrição Estadual");

        cbPais.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbPais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPais.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        cbPais.setPreferredSize(new java.awt.Dimension(185, 23));

        tfNomeFantasia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfNomeFantasia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfNomeFantasia.setPreferredSize(new java.awt.Dimension(185, 23));
        tfNomeFantasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeFantasiaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Inscrição Suframa");

        tfEndereco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfEndereco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfEndereco.setPreferredSize(new java.awt.Dimension(185, 23));
        tfEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEnderecoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Complemento");

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setText("Outro E-mail");

        tfEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfEmail.setPreferredSize(new java.awt.Dimension(185, 23));
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("País");

        tfFacebook.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfFacebook.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfFacebook.setPreferredSize(new java.awt.Dimension(185, 23));
        tfFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFacebookActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Nome Fantasia");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("CPF ou CNPJ");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("Telefone");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel21.setText("Data nascimento");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setText("Fone 3 (celular)");

        tfInscricaoMunicipal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfInscricaoMunicipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfInscricaoMunicipal.setPreferredSize(new java.awt.Dimension(185, 23));
        tfInscricaoMunicipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInscricaoMunicipalActionPerformed(evt);
            }
        });

        cbCidade.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbCidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCidade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        cbCidade.setPreferredSize(new java.awt.Dimension(185, 23));

        cbEstado.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEstado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        cbEstado.setPreferredSize(new java.awt.Dimension(185, 23));

        tfNomeResponsavel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfNomeResponsavel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfNomeResponsavel.setPreferredSize(new java.awt.Dimension(185, 23));
        tfNomeResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeResponsavelActionPerformed(evt);
            }
        });

        tfDataNascimento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        try {
            tfDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataNascimento.setPreferredSize(new java.awt.Dimension(185, 23));
        tfDataNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDataNascimentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDataNascimentoFocusLost(evt);
            }
        });

        tfFone2Fax.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        try {
            tfFone2Fax.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfFone2Fax.setPreferredSize(new java.awt.Dimension(185, 23));
        tfFone2Fax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfFone2FaxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfFone2FaxFocusLost(evt);
            }
        });

        tfFone3Celular.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        try {
            tfFone3Celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfFone3Celular.setPreferredSize(new java.awt.Dimension(185, 23));
        tfFone3Celular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfFone3CelularFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfFone3CelularFocusLost(evt);
            }
        });

        tfTelefone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        try {
            tfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfTelefone.setPreferredSize(new java.awt.Dimension(185, 23));
        tfTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTelefoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfTelefoneFocusLost(evt);
            }
        });

        tfCPFOuCNPJ.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        try {
            tfCPFOuCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCPFOuCNPJ.setPreferredSize(new java.awt.Dimension(185, 23));
        tfCPFOuCNPJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfCPFOuCNPJMousePressed(evt);
            }
        });
        tfCPFOuCNPJ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCPFOuCNPJFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCPFOuCNPJFocusLost(evt);
            }
        });

        tfCEP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        try {
            tfCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCEP.setPreferredSize(new java.awt.Dimension(185, 23));
        tfCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCEPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCEPFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfBairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfOutroEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfPalavrasChave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfFacebook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfFone2Fax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfFone3Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNomeFantasia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCPFOuCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNomeResponsavel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfInscricaoEstadual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfInscrEstaSubstTrib, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfInscricaoMunicipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfInscricaoSuframa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfComplemento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbCidade, cbEstado, cbPais, jLabel22, tfBairro, tfComplemento, tfEmail, tfEndereco, tfFacebook, tfInscrEstaSubstTrib, tfInscricaoEstadual, tfInscricaoMunicipal, tfInscricaoSuframa, tfNome, tfNomeFantasia, tfNomeResponsavel, tfNumero, tfOutroEmail, tfPalavrasChave});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(2, 2, 2)
                                .addComponent(tfNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(2, 2, 2)
                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfCPFOuCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(2, 2, 2)
                                .addComponent(tfInscrEstaSubstTrib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(2, 2, 2)
                                .addComponent(tfInscricaoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(2, 2, 2)
                                .addComponent(tfInscricaoMunicipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfInscricaoSuframa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(2, 2, 2)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(25, 25, 25))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGap(2, 2, 2)
                                .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(2, 2, 2)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16))
                                .addGap(23, 23, 23)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(26, 26, 26))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(25, 25, 25))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfFone2Fax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfFone3Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addComponent(tfOutroEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(2, 2, 2)
                                .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfFacebook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfPalavrasChave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbCidade, cbEstado, cbPais, tfFacebook});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfBairro, tfComplemento, tfEmail, tfEndereco, tfInscrEstaSubstTrib, tfInscricaoEstadual, tfInscricaoMunicipal, tfInscricaoSuframa, tfNome, tfNomeFantasia, tfNomeResponsavel, tfNumero, tfOutroEmail, tfPalavrasChave});

        rbPessoaJuridica.setText("Pessoa Jurídica");
        rbPessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPessoaJuridicaActionPerformed(evt);
            }
        });

        rbPessoaFisica.setText("Pessoa Física");
        rbPessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPessoaFisicaActionPerformed(evt);
            }
        });

        cbGrupo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbGrupo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grupo 1", "Grupo 2", "Grupo 3", "Grupo 4" }));
        cbGrupo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));

        jLabel28.setText("Grupo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(rbPessoaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbPessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbPessoaJuridica)
                        .addComponent(cbGrupo)
                        .addComponent(jLabel28))
                    .addComponent(rbPessoaFisica))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel28, rbPessoaJuridica});

        jpStatus.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(201, 239, 237)));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.gif"))); // NOI18N
        jButton3.setText("Salvar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.gif"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setPreferredSize(new java.awt.Dimension(83, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atualizar.png"))); // NOI18N
        jButton1.setText("Atualizar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jpStatusLayout = new javax.swing.GroupLayout(jpStatus);
        jpStatus.setLayout(jpStatusLayout);
        jpStatusLayout.setHorizontalGroup(
            jpStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStatusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jpStatusLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

        jpStatusLayout.setVerticalGroup(
            jpStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStatusLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(jpStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton1)))
        );

        jpStatusLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(jpStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addComponent(jpStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void tfNomeFantasiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeFantasiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeFantasiaActionPerformed

    private void tfNomeResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeResponsavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeResponsavelActionPerformed

    private void tfInscricaoEstadualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInscricaoEstadualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInscricaoEstadualActionPerformed

    private void tfInscrEstaSubstTribActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInscrEstaSubstTribActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInscrEstaSubstTribActionPerformed

    private void tfInscricaoMunicipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInscricaoMunicipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInscricaoMunicipalActionPerformed

    private void tfInscricaoSuframaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInscricaoSuframaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInscricaoSuframaActionPerformed

    private void tfEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEnderecoActionPerformed

    private void tfNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumeroActionPerformed

    private void tfComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfComplementoActionPerformed

    private void tfBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBairroActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void tfOutroEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfOutroEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfOutroEmailActionPerformed

    private void tfPalavrasChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPalavrasChaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPalavrasChaveActionPerformed

    private void tfFacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFacebookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFacebookActionPerformed

    private void cbTipoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoClienteActionPerformed
        //cbTipoCliente.setSelected(false);
        cbTipoFornecedor.setSelected(false);
        cbTipoTransportador.setSelected(false);  
        
        int selectedIndex = Home.tabHome.getSelectedIndex(); 
        Home.tabHome.setTitleAt( selectedIndex, " Cliente" );        
    }//GEN-LAST:event_cbTipoClienteActionPerformed

    private void cbTipoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoFornecedorActionPerformed
        cbTipoCliente.setSelected(false);
        //cbTipoFornecedor.setSelected(false);
        cbTipoTransportador.setSelected(false); 
        
        int selectedIndex = Home.tabHome.getSelectedIndex(); 
        Home.tabHome.setTitleAt( selectedIndex, " Fornecedor" ); 
    }//GEN-LAST:event_cbTipoFornecedorActionPerformed

    private void cbTipoTransportadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoTransportadorActionPerformed
        cbTipoCliente.setSelected(false);
        cbTipoFornecedor.setSelected(false);
        //cbTipoTransportador.setSelected(false); 
        
        int selectedIndex = Home.tabHome.getSelectedIndex(); 
        Home.tabHome.setTitleAt( selectedIndex, " Transportador" ); 
    }//GEN-LAST:event_cbTipoTransportadorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Home.ControleTabs.removerTabSelecionado();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        Setar_Grupo Setar_Grupo = new Setar_Grupo( Home, this );
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if( !tfNome.getText().trim().equals("") ) {
            
            Controle_Thread_Contato t1 = new Controle_Thread_Contato( Home, this );        
            t1.setName("Controle Thread Contato");         
            t1.start(); 
        }
        else{
            JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "O Campo Nome ou Razão social não pode ser nulo", "Nome ou Razão social?" );
            tfNome.requestFocus();
        }
    }//GEN-LAST:event_jButton3ActionPerformed
        
    private void tfTelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTelefoneFocusGained
        setarFocusGainedTelefone( tfTelefone );
    }//GEN-LAST:event_tfTelefoneFocusGained

    private void tfTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTelefoneFocusLost
        setarFocusLostTelefone( tfTelefone );
    }//GEN-LAST:event_tfTelefoneFocusLost

    private void tfFone2FaxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFone2FaxFocusGained
        setarFocusGainedTelefone( tfFone2Fax );
    }//GEN-LAST:event_tfFone2FaxFocusGained

    private void tfFone2FaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFone2FaxFocusLost
        setarFocusLostTelefone( tfFone2Fax );
    }//GEN-LAST:event_tfFone2FaxFocusLost

    private void tfFone3CelularFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFone3CelularFocusGained
        setarFocusGainedTelefone( tfFone3Celular );
    }//GEN-LAST:event_tfFone3CelularFocusGained

    private void tfFone3CelularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFone3CelularFocusLost
        setarFocusLostTelefone( tfFone3Celular );
    }//GEN-LAST:event_tfFone3CelularFocusLost

    private void tfDataNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDataNascimentoFocusGained
        setarFocusGainedData( tfDataNascimento );
    }//GEN-LAST:event_tfDataNascimentoFocusGained

    private void tfDataNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDataNascimentoFocusLost
        setarFocusLostData( tfDataNascimento );
    }//GEN-LAST:event_tfDataNascimentoFocusLost

    private void rbPessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPessoaFisicaActionPerformed
        tfCPFOuCNPJ.setValue("");
        rbPessoaJuridica.setSelected(false);
        rbPessoaFisicaMascara(); 
    }//GEN-LAST:event_rbPessoaFisicaActionPerformed

    private void rbPessoaFisicaMascara(){                                               
        try {
                
                MaskFormatter mascara = new MaskFormatter("###.###.###-##");
                mascara.setValidCharacters("0123456789");
                
                tfCPFOuCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascara ) );                
            } catch ( Exception e ) {
                JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        tfCPFOuCNPJ.requestFocus();
            } 
    }
    
    private void rbPessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPessoaJuridicaActionPerformed
        tfCPFOuCNPJ.setValue("");
        rbPessoaFisica.setSelected(false);
        rbPessoaJuridicaMascara();
        
    }//GEN-LAST:event_rbPessoaJuridicaActionPerformed

    private void rbPessoaJuridicaMascara(){                                               
        try {
                
                MaskFormatter mascaraTelefone = new MaskFormatter("##.###.###/####-##");
                mascaraTelefone.setValidCharacters("0123456789");
                
                tfCPFOuCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascaraTelefone ) );                
            } catch ( Exception e ) {
                JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        tfCPFOuCNPJ.requestFocus();
            }
    }
    
    private void tfCPFOuCNPJMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCPFOuCNPJMousePressed
        if( rbPessoaJuridica.isSelected() || rbPessoaFisica.isSelected() ){                       
        }
        else{
            
            JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "O Campo Pessoa Física ou Jurídica não pode ser nulo"
                    + "\nEscolha um dos ítens"
                    + "\nExemplo:"
                    + "\n    Pessoa Física"
                    + "\n    Pessoa Jurídica"
                    , "Pessoa Física ou Jurídica" );
            rbPessoaFisica.requestFocus();
        }
    }//GEN-LAST:event_tfCPFOuCNPJMousePressed

    private void tfCPFOuCNPJFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCPFOuCNPJFocusGained
        if( rbPessoaJuridica.isSelected() || rbPessoaFisica.isSelected() ){ 
            
            if( rbPessoaFisica.isSelected() ){
                
                setarFocusGainedCPF( tfCPFOuCNPJ );
            }
            else if( rbPessoaJuridica.isSelected() ){
            
                setarFocusGainedCNPJ( tfCPFOuCNPJ );
            }
        }
    }//GEN-LAST:event_tfCPFOuCNPJFocusGained

    private void tfCPFOuCNPJFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCPFOuCNPJFocusLost
        if( rbPessoaJuridica.isSelected() || rbPessoaFisica.isSelected() ){ 
            
            if( rbPessoaFisica.isSelected() ){
                
                setarFocusLostCPF( tfCPFOuCNPJ );    
            }
            else if( rbPessoaJuridica.isSelected() ){
            
                setarFocusLostCNPJ( tfCPFOuCNPJ );
            }
        }
    }//GEN-LAST:event_tfCPFOuCNPJFocusLost

    private void tfCEPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCEPFocusGained
        setarFocusGainedCEP( tfCEP );
    }//GEN-LAST:event_tfCEPFocusGained

    private void tfCEPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCEPFocusLost
        setarFocusLostCEP( tfCEP );
    }//GEN-LAST:event_tfCEPFocusLost
   
    
    private void setarFocusGainedTelefone( JFormattedTextField ftm ) {
        if( ftm.getText().trim().equals("") || ftm.getText().trim().equals("+    (    )      -") ){   
            
            try {
                
                MaskFormatter mascaraTelefone = new MaskFormatter("+ ## ( ## ) #### - ####");
                mascaraTelefone.setValidCharacters("0123456789");
                
                ftm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascaraTelefone ) );                
            } catch ( Exception e ) {
                JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        tfCPFOuCNPJ.requestFocus();
            }
            ftm.setText( "5585" );            
        }                
    } 
    
    public void setarFocusLostTelefone( JFormattedTextField ftm ) {
                
        if( !ftm.getText().trim().equals("") ){  
            
            if( ftm.getText().trim().length() < 23 ){ ftm.setValue( "" );
                
                try {                    
                    MaskFormatter mascaraTelefone = new MaskFormatter(""); 
                    ftm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascaraTelefone ) );
                    ftm.setText( "" ); 
                } catch ( Exception e ) {
                    JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        tfCPFOuCNPJ.requestFocus();
                }
            }
        }              
    }
    
    private void setarFocusGainedData( JFormattedTextField ftm ) {
        if( ftm.getText().trim().equals("") || ftm.getText().trim().equals("   /    /") ){   
            
            try {
                
                MaskFormatter mascaraTelefone = new MaskFormatter("## / ## / ####");
                mascaraTelefone.setValidCharacters("0123456789");
                
                ftm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascaraTelefone ) );                
            } catch ( Exception e ) {
                JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        tfCPFOuCNPJ.requestFocus();
            }
            ftm.setText( "" );            
        }                
    }
    
    public void setarFocusLostData( JFormattedTextField ftm ) {
                
        if( !ftm.getText().trim().equals("") ){  
            
            if( ftm.getText().trim().length() < 14 ){ ftm.setValue( "" );
                
                try {                    
                    MaskFormatter mascaraTelefone = new MaskFormatter(""); 
                    ftm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascaraTelefone ) );
                    ftm.setText( "" ); 
                } catch ( Exception e ) {
                    JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        tfCPFOuCNPJ.requestFocus();
                }
            }
        }              
    }
    
    private void setarFocusGainedCNPJ( JFormattedTextField ftm ) {
        if( ftm.getText().trim().equals("") || ftm.getText().trim().equals(".   .   /    -") ){   
            
            try {
                
                MaskFormatter mascaraTelefone = new MaskFormatter("##.###.###/####-##");
                mascaraTelefone.setValidCharacters("0123456789");
                
                ftm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascaraTelefone ) );                
            } catch ( Exception e ) {
                JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        tfCPFOuCNPJ.requestFocus();
            }
            ftm.setText( "" );            
        }                
    }
    
    public void setarFocusLostCNPJ( JFormattedTextField ftm ) {
                
        if( !ftm.getText().trim().equals("") ){  
            
            if( ftm.getText().trim().length() < 18 ){ ftm.setValue( "" );
                
                try {                    
                    MaskFormatter mascara = new MaskFormatter(""); 
                    ftm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascara ) );
                    ftm.setText( "" ); 
                } catch ( Exception e ) {
                    JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        tfCPFOuCNPJ.requestFocus();
                }
            }
        }              
    }
    
    private void setarFocusGainedCPF( JFormattedTextField ftm ) {
        if( ftm.getText().trim().equals("") || ftm.getText().trim().equals(".   .   -") ){   
            
            try {
                
                MaskFormatter mascara = new MaskFormatter("###.###.###-##");
                mascara.setValidCharacters("0123456789");
                
                ftm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascara ) );                
            } catch ( Exception e ) {
                JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        tfCPFOuCNPJ.requestFocus();
            }
            ftm.setText( "" );            
        }                
    }
    
    public void setarFocusLostCPF( JFormattedTextField ftm ) {
                
        if( !ftm.getText().trim().equals("") ){  
            
            if( ftm.getText().trim().length() < 14 ){ ftm.setValue( "" );
                
                try {                    
                    MaskFormatter mascara = new MaskFormatter(""); 
                    ftm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascara ) );
                    ftm.setText( "" ); 
                } catch ( Exception e ) {
                    JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        tfCPFOuCNPJ.requestFocus();
                }
            }
        }              
    }
    
    private void setarFocusGainedCEP( JFormattedTextField ftm ) {
        if( ftm.getText().trim().equals("") || ftm.getText().trim().equals("  .   -") ){   
            
            try {
                
                MaskFormatter mascara = new MaskFormatter("##.###-###");
                mascara.setValidCharacters("0123456789");
                
                ftm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascara ) );                
            } catch ( Exception e ) {
                JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        tfCPFOuCNPJ.requestFocus();
            }
            ftm.setText( "" );            
        }                
    }
    
    public void setarFocusLostCEP( JFormattedTextField ftm ) {
                
        if( !ftm.getText().trim().equals("") ){  
            
            if( ftm.getText().trim().length() < 10 ){ ftm.setValue( "" );
                
                try {                    
                    MaskFormatter mascara = new MaskFormatter(""); 
                    ftm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascara ) );
                    ftm.setText( "" ); 
                } catch ( Exception e ) {
                    JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        tfCPFOuCNPJ.requestFocus();
                }
            }
        }              
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox cbCidade;
    public javax.swing.JComboBox cbEstado;
    public javax.swing.JComboBox cbGrupo;
    public javax.swing.JComboBox cbPais;
    public javax.swing.JRadioButton cbTipoCliente;
    public javax.swing.JRadioButton cbTipoFornecedor;
    public javax.swing.JRadioButton cbTipoTransportador;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpStatus;
    public javax.swing.JRadioButton rbPessoaFisica;
    public javax.swing.JRadioButton rbPessoaJuridica;
    public javax.swing.JTextArea taAnotacoesGerais;
    public javax.swing.JTextField tfBairro;
    public javax.swing.JFormattedTextField tfCEP;
    public javax.swing.JFormattedTextField tfCPFOuCNPJ;
    public javax.swing.JTextField tfComplemento;
    public javax.swing.JFormattedTextField tfDataNascimento;
    public javax.swing.JTextField tfEmail;
    public javax.swing.JTextField tfEndereco;
    public javax.swing.JTextField tfFacebook;
    public javax.swing.JFormattedTextField tfFone2Fax;
    public javax.swing.JFormattedTextField tfFone3Celular;
    public javax.swing.JTextField tfInscrEstaSubstTrib;
    public javax.swing.JTextField tfInscricaoEstadual;
    public javax.swing.JTextField tfInscricaoMunicipal;
    public javax.swing.JTextField tfInscricaoSuframa;
    public javax.swing.JTextField tfNome;
    public javax.swing.JTextField tfNomeFantasia;
    public javax.swing.JTextField tfNomeResponsavel;
    public javax.swing.JTextField tfNumero;
    public javax.swing.JTextField tfOutroEmail;
    public javax.swing.JTextField tfPalavrasChave;
    public javax.swing.JFormattedTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
    
    Eventos_Clientes_CB_Estados Ev_Clientes_CB_Estado = new Eventos_Clientes_CB_Estados( this );
    private void setarEventosComboBoxs(){
        
        Ev_Clientes_CB_Estado.cbEstados( cbEstado );
        
    }
    
    public void setarComboBoxPais( String pais ){
        
        Pais_Estado_Cidade P_E_C = new Pais_Estado_Cidade();
                
        cbPais.removeAllItems();                                        // "pais"
        DefaultComboBoxModel model = new DefaultComboBoxModel( P_E_C.setar( pais ) );  
        cbPais.setModel( model );
    }
    
    public void setarComboBoxEstado( String pais_estados ){
        
        Pais_Estado_Cidade P_E_C = new Pais_Estado_Cidade();

        cbEstado.removeAllItems();                                      // "Pais_estados"
        DefaultComboBoxModel model = new DefaultComboBoxModel( P_E_C.setar( pais_estados ) );  
        cbEstado.setModel( model );
        
        cbEstado.setSelectedIndex( 5 ); // Ítem 5 = Ceará
    }
    
    public void setarComboBoxCidade( String pais_estado_cidades ){
        
        Pais_Estado_Cidade P_E_C = new Pais_Estado_Cidade();

        cbCidade.removeAllItems();                                       // "Pais_estado_cidades"
        DefaultComboBoxModel model = new DefaultComboBoxModel( P_E_C.setar( pais_estado_cidades ) );  
        cbCidade.setModel( model );
        
        cbCidade.setSelectedIndex( 58 ); // Ítem 58 = Fortaleza
    }
            
}
