/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package definicao_forma_pgto;

import OS.OS;
import OS_Forma_de_Pagamento.Bean_OS_Contas_Disponiveis;
import OS_Forma_de_Pagamento.Bean_OS_Forma_de_Pagamento;
import OS_Forma_de_Pagamento.Bean_OS_TipoDeDocumento;
import definicao_forma_pgto_Setar_CB_Forma_Pgto.BookInfo_OS_Forma_de_Pgto;
import definicao_forma_pgto_Setar_CB_Parcelas.BookInfo_Parcelas_Forma_de_Pagamento;
import definicao_forma_pgto_Setar_CB_Parcelas.GetIntParcelamentoMaximo;
import definicao_forma_pgto_Setar_CB_Parcelas.Setar_CB_Parcelas_EVT_CB_Forma_Pgto;
import definicao_forma_pgto_controle.ControleThread_Eventos;
import definicao_forma_pgto_controle.Setar_Parcelas;
import definicao_forma_pgto_parcelas.Topo_Preenchimento_da_Lista;
import home.Home;
import java.awt.Color;
import utilidades.JOptionPaneMod;
import utilidades.RetornarNumeroFloat;

/**
 *
 * @author AnaMariana
 */
public class OS_Definir_Forma_de_Pagamento extends javax.swing.JPanel {
    
    public Topo_Preenchimento_da_Lista Topo_Preenchimento_da_Lista = new Topo_Preenchimento_da_Lista();
    /**
     * Creates new form Cliente
     */
    OS OS;
    Home Home;
    OS_Definir_Forma_de_Pagamento_Home OS_Definir_Forma_de_Pagamento_Home;
    
    public float Total;        
    Bean_OS_Contas_Disponiveis Bean_Conta;        
    Bean_OS_TipoDeDocumento    Bean_Documento;        
    Bean_OS_Forma_de_Pagamento Bean_Forma_Pgto;
    
    public OS_Definir_Forma_de_Pagamento( 
            Home Home2, OS OS2,OS_Definir_Forma_de_Pagamento_Home OS_Definir_Forma_de_Pagamento_Home2,
            float Total2, 
            Bean_OS_Contas_Disponiveis Bean_Conta2,
            Bean_OS_TipoDeDocumento Bean_Documento2, 
            Bean_OS_Forma_de_Pagamento Bean_Forma_Pgto2 ) {
        
        OS = OS2;
        Home = Home2;
        OS_Definir_Forma_de_Pagamento_Home = OS_Definir_Forma_de_Pagamento_Home2;
        
        Total           = Total2;        
        Bean_Conta      = Bean_Conta2;        
        Bean_Documento  = Bean_Documento2;        
        Bean_Forma_Pgto = Bean_Forma_Pgto2;
        
        initComponents();
        
        cbFormaDePagamento.setBackground( new Color( 255, 255, 255 ) );
        cbParcelas.setBackground        ( new Color( 255, 255, 255 ) );
        cbTipoDeEntrada.setBackground   ( new Color( 255, 255, 255 ) );
        cbTipoDeDesconto.setBackground  ( new Color( 255, 255, 255 ) );
                
        inicio( Home, OS, Total, Bean_Conta, Bean_Documento, Bean_Forma_Pgto );
    }
    
    public void setarParcelas( 
            Home Home2, OS OS2,
            float Total2, 
            Bean_OS_Contas_Disponiveis Bean_Conta2,
            Bean_OS_TipoDeDocumento Bean_Documento2, 
            Bean_OS_Forma_de_Pagamento Bean_Forma_Pgto2 ) {
        
        //System.out.println( "*************setarParcelas   " + Bean_Forma_Pgto2.getPARCELAMENTOMAXIMO() );
        
        Setar_Parcelas Setar_Parcelas = new Setar_Parcelas( 
                Home2, OS2, this, Total2, Bean_Conta2, Bean_Documento2, Bean_Forma_Pgto2 );    
        
        Setar_Parcelas.inicio();
        
    }
    
    private void inicio( 
            Home Home2, OS OS2,
            float Total2, 
            Bean_OS_Contas_Disponiveis Bean_Conta2,
            Bean_OS_TipoDeDocumento Bean_Documento2, 
            Bean_OS_Forma_de_Pagamento Bean_Forma_Pgto2 ) {
        
        OS_Definir_Forma_de_Pagamento_Inicio OS_Definir_Forma_de_Pagamento_Inicio = new OS_Definir_Forma_de_Pagamento_Inicio( 
                Home2, OS2, this, Total2, Bean_Conta2, Bean_Documento2, Bean_Forma_Pgto2 );    
        
        OS_Definir_Forma_de_Pagamento_Inicio.inicio();

        Parcelas_OS_Definir_Forma_de_Pagamento.setVisible( OS.pegar_e_GetFINANCEIRO() );
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfValorEntrada = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        chTaxaFixa = new javax.swing.JCheckBox();
        chJuros = new javax.swing.JCheckBox();
        cbFormaDePagamento = new javax.swing.JComboBox();
        cbParcelas = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cbTipoDeEntrada = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cbTipoDeDesconto = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        tfValorDesconto = new javax.swing.JTextField();
        lbNomeDoValorDedesconto = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbFormaDePagamento = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbValorAvista = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbTotalEsquerdo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btAtualizar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btCancelar1 = new javax.swing.JButton();
        Parcelas_OS_Definir_Forma_de_Pagamento = new javax.swing.JPanel();
        jpResolverProblema = new javax.swing.JPanel();
        chResolverFinanceiro = new javax.swing.JCheckBox();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Definindo a forma de pagamento");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Forma de pagamento");

        tfValorEntrada.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfValorEntrada.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfValorEntrada.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfValorEntrada.setPreferredSize(new java.awt.Dimension(130, 23));
        tfValorEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfValorEntradaKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Valor entrada ($)");

        chTaxaFixa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chTaxaFixa.setText("Taxa fixa ( $ 0,00 )");
        chTaxaFixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chTaxaFixaMousePressed(evt);
            }
        });

        chJuros.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chJuros.setText("Juros ( 0,00 % )");
        chJuros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chJurosMousePressed(evt);
            }
        });

        cbFormaDePagamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbFormaDePagamento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        cbFormaDePagamento.setPreferredSize(new java.awt.Dimension(219, 25));
        cbFormaDePagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFormaDePagamentoActionPerformed(evt);
            }
        });

        cbParcelas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbParcelas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        cbParcelas.setPreferredSize(new java.awt.Dimension(219, 23));
        cbParcelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbParcelasActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Parcelas");

        cbTipoDeEntrada.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbTipoDeEntrada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sem entrada", "Com entrada igual", "Com entrada diferente" }));
        cbTipoDeEntrada.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        cbTipoDeEntrada.setPreferredSize(new java.awt.Dimension(219, 23));
        cbTipoDeEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoDeEntradaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Tipo de entrada");

        cbTipoDeDesconto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbTipoDeDesconto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sem desconto", "Desconto em porcentagem", "Desconto em valor" }));
        cbTipoDeDesconto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        cbTipoDeDesconto.setPreferredSize(new java.awt.Dimension(219, 23));
        cbTipoDeDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoDeDescontoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Tipo de desconto");

        tfValorDesconto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfValorDesconto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfValorDesconto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfValorDesconto.setPreferredSize(new java.awt.Dimension(161, 23));
        tfValorDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValorDescontoActionPerformed(evt);
            }
        });
        tfValorDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfValorDescontoFocusLost(evt);
            }
        });
        tfValorDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfValorDescontoKeyReleased(evt);
            }
        });

        lbNomeDoValorDedesconto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbNomeDoValorDedesconto.setText("Valor Desconto ");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Resumo");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Forma de pgto:");

        lbFormaDePagamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbFormaDePagamento.setForeground(new java.awt.Color(102, 102, 102));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("A vista, no valor de R$");

        lbValorAvista.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbValorAvista.setForeground(new java.awt.Color(153, 153, 153));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Total: R$");

        lbTotalEsquerdo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbTotalEsquerdo.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalEsquerdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbFormaDePagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbValorAvista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbValorAvista, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTotalEsquerdo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel11, jLabel14, jLabel16, lbFormaDePagamento, lbTotalEsquerdo, lbValorAvista});

        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atualizar.png"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btAtualizarMousePressed(evt);
            }
        });

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.gif"))); // NOI18N
        btCancelar.setText("Salvar");
        btCancelar.setPreferredSize(new java.awt.Dimension(96, 29));

        btCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        btCancelar1.setText("Selecionar");
        btCancelar1.setPreferredSize(new java.awt.Dimension(96, 25));
        btCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btAtualizar)
                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btAtualizar, btCancelar, btCancelar1});

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbTipoDeDesconto, 0, 308, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chTaxaFixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chJuros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbFormaDePagamento, 0, 309, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbParcelas, 0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbTipoDeEntrada, 0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfValorEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfValorDesconto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbNomeDoValorDedesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {chJuros, chTaxaFixa});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lbNomeDoValorDedesconto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfValorDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 80, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipoDeDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chJuros))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(cbParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbTipoDeEntrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfValorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chTaxaFixa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbFormaDePagamento, cbParcelas, cbTipoDeDesconto, cbTipoDeEntrada, tfValorDesconto, tfValorEntrada});

        javax.swing.GroupLayout Parcelas_OS_Definir_Forma_de_PagamentoLayout = new javax.swing.GroupLayout(Parcelas_OS_Definir_Forma_de_Pagamento);
        Parcelas_OS_Definir_Forma_de_Pagamento.setLayout(Parcelas_OS_Definir_Forma_de_PagamentoLayout);
        Parcelas_OS_Definir_Forma_de_PagamentoLayout.setHorizontalGroup(
            Parcelas_OS_Definir_Forma_de_PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Parcelas_OS_Definir_Forma_de_PagamentoLayout.setVerticalGroup(
            Parcelas_OS_Definir_Forma_de_PagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );

        chResolverFinanceiro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chResolverFinanceiro.setText("Desejo resolver o financeiro agora");
        chResolverFinanceiro.setPreferredSize(new java.awt.Dimension(802, 23));
        chResolverFinanceiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chResolverFinanceiroMousePressed(evt);
            }
        });
        chResolverFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chResolverFinanceiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpResolverProblemaLayout = new javax.swing.GroupLayout(jpResolverProblema);
        jpResolverProblema.setLayout(jpResolverProblemaLayout);
        jpResolverProblemaLayout.setHorizontalGroup(
            jpResolverProblemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpResolverProblemaLayout.createSequentialGroup()
                .addComponent(chResolverFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );
        jpResolverProblemaLayout.setVerticalGroup(
            jpResolverProblemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chResolverFinanceiro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Parcelas_OS_Definir_Forma_de_Pagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jpResolverProblema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpResolverProblema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Parcelas_OS_Definir_Forma_de_Pagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfValorDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValorDescontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfValorDescontoActionPerformed

    private void btCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelar1ActionPerformed
            
    }//GEN-LAST:event_btCancelar1ActionPerformed

    private void btAtualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAtualizarMousePressed
      
    }//GEN-LAST:event_btAtualizarMousePressed

    private void cbFormaDePagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFormaDePagamentoActionPerformed
        try{
            //MeuObjeto obj = (MeuObjeto) combobox.getSelectedItem();
            if( cbFormaDePagamento.getSelectedItem() != null ) {
                
                
                BookInfo_OS_Forma_de_Pgto obj = (BookInfo_OS_Forma_de_Pgto) cbFormaDePagamento.getSelectedItem();
                
                Bean_OS_Forma_de_Pagamento Bean_Forma_Pgto_CB = new Bean_OS_Forma_de_Pagamento();
        
                Bean_Forma_Pgto_CB.setID                                    ( obj.ID );                    
                Bean_Forma_Pgto_CB.setNOME                                  ( obj.NOME );
                Bean_Forma_Pgto_CB.setPARCELAMENTOMAXIMO                    ( obj.PARCELAMENTOMAXIMO );
                Bean_Forma_Pgto_CB.setPARCELASSEMJUROS                      ( obj.PARCELASSEMJUROS );                    
                Bean_Forma_Pgto_CB.setJUROSPORCENTAGEM                      ( obj.JUROSPORCENTAGEM );
                Bean_Forma_Pgto_CB.setTAXAFIXA                              ( obj.TAXAFIXA );
                Bean_Forma_Pgto_CB.setDESCONTOAVISTAPORCENTAGEM             ( obj.DESCONTOAVISTAPORCENTAGEM );                    
                Bean_Forma_Pgto_CB.setCONTADEDESTINOPADRAOID                ( obj.CONTADEDESTINOPADRAOID );                    
                Bean_Forma_Pgto_CB.setTIPODEDOCUMENTOPADRAOID               ( obj.TIPODEDOCUMENTOPADRAOID );                    
                Bean_Forma_Pgto_CB.setINTERVALOPADRAOENTREASPARCELAS        ( obj.INTERVALOPADRAOENTREASPARCELAS );
                Bean_Forma_Pgto_CB.setINTERVALOPADRAOENTREASPARCELASDIAOUMES( obj.INTERVALOPADRAOENTREASPARCELASDIAOUMES );
                
                Bean_OS_Contas_Disponiveis Bean_Conta = new Bean_OS_Contas_Disponiveis();
        
                Bean_Conta.setID                  ( obj.CONTADEDESTINOPADRAOID );
                Bean_Conta.setAPELIDOCURTO        ( OS.APELIDOCURTO );
                Bean_Conta.setNOMEDESCRICAODACONTA( OS.NOMEDESCRICAODACONTA );
                
                Bean_OS_TipoDeDocumento Bean_Doc = new Bean_OS_TipoDeDocumento();
        
                Bean_Doc.setID           ( obj.TIPODEDOCUMENTOPADRAOID );                    
                Bean_Doc.setNOME         ( OS.NOMETIPODEDOCUMENTO );
                Bean_Doc.setTIPODECUSTO  ( OS.TIPODECUSTO );
                Bean_Doc.setVALORDECUSTO ( OS.VALORDECUSTO );
                
                OS.receber_e_SetarConta    ( Bean_Conta );
                OS.receber_e_SetarDocumento( Bean_Doc );
                OS.receber_e_SetarFormaPgto( Bean_Forma_Pgto_CB );
                
                                
                GetIntParcelamentoMaximo GetIntParcelamentoMaximo = new GetIntParcelamentoMaximo();                
                Setar_CB_Parcelas_EVT_CB_Forma_Pgto Setar_CB_Parcelas = new Setar_CB_Parcelas_EVT_CB_Forma_Pgto(
                    
                        OS,GetIntParcelamentoMaximo.getInt( obj.PARCELAMENTOMAXIMO ), Home, this 
                );
                
                
                OS.receber_e_SetarQTDParcelas( 0 );
                cbTipoDeEntrada.setSelectedIndex( 0 );
                OS.receber_e_SetarCBTIPODEENTRADASELECIONADO( 0 );
                
                OS.receber_e_SetarValorDeEntrada( 0 );
                tfValorEntrada.setText( "" );
                tfValorEntrada.setEnabled( false );
                
                chJuros   .setText( "Juros ( "+obj.JUROSPORCENTAGEM+" % )" );
                chTaxaFixa.setText( "Taxa fixa ( $ "+obj.TAXAFIXA+" )" );
                
                
                CBParcelas();
                CBTipoDeEntrada_CBTipoDeDesconto();
                
                
                
                ControleThread_Eventos t1 = new ControleThread_Eventos( OS, Home, this ); 
        
                t1.setName("ControleThread_Eventos");   
        
                t1.start();
            }
                    
            
        }catch(Exception e) {
            JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Definir_Forma_de_Pagamento, "
                    + "\ncbFormaDePagamentoActionPerformed(java.awt.event.ActionEvent evt)"
                    + e.getMessage()
                    + "\n", "cbFormaDePagamentoActionPerformed(java.awt.event.ActionEvent evt)" );
        }
    }//GEN-LAST:event_cbFormaDePagamentoActionPerformed

    private void CBParcelas(){
        
        if( OS.pegar_e_GetQTDParcelas() == 0 ) {
            
            cbTipoDeEntrada.setEnabled( false );
        }
        else{
            
            cbTipoDeEntrada.setEnabled( true );
        }
    }
    
    private void CBTipoDeEntrada_CBTipoDeDesconto(){
        
        if( OS.pegar_e_GetCBTIPODEENTRADASELECIONADO() == 0 ) {
            
            tfValorEntrada.setText( "" );
            tfValorEntrada.setEnabled( false );
            cbTipoDeEntrada.setSelectedIndex( OS.pegar_e_GetCBTIPODEENTRADASELECIONADO() );
        } 
        else{
            
            tfValorEntrada.setEnabled( true );
            tfValorEntrada.setText( String.valueOf( OS.pegar_e_GetValorDeEntrada() ) );
            cbTipoDeEntrada.setSelectedIndex( OS.pegar_e_GetCBTIPODEENTRADASELECIONADO() );
        }
        
        if( OS.pegar_e_GetCBTIPODEDESCONTO() == 0 ) {
            
            tfValorDesconto.setText( "" );
            tfValorDesconto.setEnabled( false );
            cbTipoDeDesconto.setSelectedIndex( OS.pegar_e_GetCBTIPODEDESCONTO() );
            
        }
        else{
            
            tfValorDesconto.setEnabled( true );
            tfValorDesconto.setText( String.valueOf( OS.pegar_e_GetVALORDEDESCONTO() ) );
            cbTipoDeDesconto.setSelectedIndex( OS.pegar_e_GetCBTIPODEDESCONTO() );
        }
        
    }
    
    private void cbParcelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbParcelasActionPerformed
        try{
            //MeuObjeto obj = (MeuObjeto) combobox.getSelectedItem();
            if( cbParcelas.getSelectedItem() != null ) {
                
                BookInfo_Parcelas_Forma_de_Pagamento obj = (BookInfo_Parcelas_Forma_de_Pagamento) cbParcelas.getSelectedItem();
        
                OS.receber_e_SetarCBPARCELASSELECIONADO                     ( obj.CODIGO );   
                
                try{
                    
                    String numeroParcelas = cbParcelas.getSelectedItem().toString(); 
                                       
                    int qtdParc = Integer.parseInt( numeroParcelas );
                    OS.receber_e_SetarQTDParcelas( qtdParc-1 );
                    //System.out.println("OS.receber_e_SetarQTDParcelas   " + numeroParcelas );
                }catch(Exception e) {
                    
                    OS.receber_e_SetarQTDParcelas( 0 );
                    //System.out.println("OS.receber_e_SetarQTDParcelas   " + OS_Definir_Forma_de_Pagamento.cbParcelas.getSelectedItem().toString() );
                }
                
                cbTipoDeEntrada.setSelectedIndex( 0 );
                OS.receber_e_SetarCBTIPODEENTRADASELECIONADO( 0 );
                
                OS.receber_e_SetarValorDeEntrada( 10 );
                tfValorEntrada.setText( "" );
                tfValorEntrada.setEnabled( false );
                
                
                
                CBParcelas();
                CBTipoDeEntrada_CBTipoDeDesconto();
                
                
                
                ControleThread_Eventos t1 = new ControleThread_Eventos( OS, Home, this ); 
        
                t1.setName("ControleThread_Eventos");   
        
                t1.start();
            }
                    
            
        }catch(Exception e) {
            JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Definir_Forma_de_Pagamento, "
                    + "\ncbFormaDePagamentoActionPerformed(java.awt.event.ActionEvent evt)"
                    + e.getMessage()
                    + "\n", "cbFormaDePagamentoActionPerformed(java.awt.event.ActionEvent evt)" );
        }
    }//GEN-LAST:event_cbParcelasActionPerformed

    private void cbTipoDeEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoDeEntradaActionPerformed
        try{
                //MeuObjeto obj = (MeuObjeto) combobox.getSelectedItem();
                if( cbTipoDeEntrada.getSelectedItem() != null && cbTipoDeEntrada.isEnabled() ) {

                    String tipoDeEntrada = cbTipoDeEntrada.getSelectedItem().toString(); 
                                                            
                    if( tipoDeEntrada.equals("Com entrada diferente") ){
                        OS.receber_e_SetarCBTIPODEENTRADASELECIONADO( 2 );
                        
                        tfValorEntrada.setText( "" );
                        tfValorEntrada.setEnabled( true );
                        OS.receber_e_SetarValorDeEntrada ( 0 );
                    }
                    else if( tipoDeEntrada.equals("Com entrada igual") ){
                        OS.receber_e_SetarCBTIPODEENTRADASELECIONADO( 1 );
                        
                        tfValorEntrada.setText( "" );
                        tfValorEntrada.setEnabled( false );
                        OS.receber_e_SetarValorDeEntrada ( Total / OS.pegar_e_GetQTDParcelas() );
                        System.out.println( "tipoDeEntrada    " + "Total " + Total + " "+ "OS.pegar_e_GetQTDParcelas() + 1 " + OS.pegar_e_GetQTDParcelas() + " "+OS.pegar_e_GetValorDeEntrada() );                        
                    }
                    else{
                        OS.receber_e_SetarCBTIPODEENTRADASELECIONADO( 0 );
                        
                        tfValorEntrada.setText( "" );
                        tfValorEntrada.setEnabled( false );
                        OS.receber_e_SetarValorDeEntrada ( 0 );
                    }   
                                                        
            }
            
            }catch(Exception e) {
                JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "ControleThread_Eventos, "
                    + "\nz()"
                    + e.getMessage()
                    + "\n", "z())" );
            }
        
        setarParcelas( Home, OS, Total, OS.pegar_e_GetConta(), OS.pegar_e_GetDocumento(), OS.pegar_e_GetarFormaPgto() );

    }//GEN-LAST:event_cbTipoDeEntradaActionPerformed

    private void cbTipoDeDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoDeDescontoActionPerformed
        try{
                //MeuObjeto obj = (MeuObjeto) combobox.getSelectedItem();
                if( cbTipoDeDesconto.getSelectedItem() != null && cbTipoDeDesconto.isEnabled() ) {

                    String tipoDeDesconto = cbTipoDeDesconto.getSelectedItem().toString(); 
                                                            
                    if( tipoDeDesconto.equals("Sem desconto") ){
                        OS.receber_e_SetarCBTIPODEDESCONTO( 0 );
                        
                        tfValorDesconto.setText( "" );
                        tfValorDesconto.setEnabled( false );
                        OS.receber_e_SetarVALORDEDESCONTO ( 0 );
                    }
                    else if( tipoDeDesconto.equals("Desconto em porcentagem") ){
                        OS.receber_e_SetarCBTIPODEDESCONTO( 1 );
                        
                        tfValorDesconto.setText( "" );
                        tfValorDesconto.setEnabled( true );
                        OS.receber_e_SetarVALORDEDESCONTO ( 0 );                                                
                    }
                    else{
                        OS.receber_e_SetarCBTIPODEDESCONTO( 2 );
                        
                        tfValorDesconto.setText( "" );
                        tfValorDesconto.setEnabled( true );
                        OS.receber_e_SetarVALORDEDESCONTO ( 0 );
                    }   
                                                        
            }
            
            }catch(Exception e) {
                JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "ControleThread_Eventos, "
                    + "\nz()"
                    + e.getMessage()
                    + "\n", "z())" );
            }
        
        setarParcelas( Home, OS, Total, OS.pegar_e_GetConta(), OS.pegar_e_GetDocumento(), OS.pegar_e_GetarFormaPgto() );
    }//GEN-LAST:event_cbTipoDeDescontoActionPerformed

    private void tfValorDescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfValorDescontoFocusLost

    }//GEN-LAST:event_tfValorDescontoFocusLost

    boolean chJurospermitirAcesso = false;
    private void chJurosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chJurosMousePressed
        if( chJurospermitirAcesso == true ) {
            chJurospermitirAcesso = false;
            
            OS.receber_e_SetarCHJUROSPORCENTAGEM( false );
          
            setarParcelas( Home, OS, Total, OS.pegar_e_GetConta(), OS.pegar_e_GetDocumento(), OS.pegar_e_GetarFormaPgto() );
        } else if( chJurospermitirAcesso == false ) {
            chJurospermitirAcesso = true;
            
            OS.receber_e_SetarCHJUROSPORCENTAGEM( true );
            
            setarParcelas( Home, OS, Total, OS.pegar_e_GetConta(), OS.pegar_e_GetDocumento(), OS.pegar_e_GetarFormaPgto() );
        }    
    }//GEN-LAST:event_chJurosMousePressed

    boolean CHTAXAFIXApermitirAcesso = false;
    private void chTaxaFixaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chTaxaFixaMousePressed
        if( CHTAXAFIXApermitirAcesso == true ) {
            CHTAXAFIXApermitirAcesso = false;
            
            OS.receber_e_SetarCHTAXAFIXA( false );
          
            setarParcelas( Home, OS, Total, OS.pegar_e_GetConta(), OS.pegar_e_GetDocumento(), OS.pegar_e_GetarFormaPgto() );
        } else if( CHTAXAFIXApermitirAcesso == false ) {
            CHTAXAFIXApermitirAcesso = true;
            
            OS.receber_e_SetarCHTAXAFIXA( true );

            setarParcelas( Home, OS, Total, OS.pegar_e_GetConta(), OS.pegar_e_GetDocumento(), OS.pegar_e_GetarFormaPgto() );
        } 
    }//GEN-LAST:event_chTaxaFixaMousePressed

    private void chResolverFinanceiroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chResolverFinanceiroMousePressed
        configurarCbPermitirAcesso();
    }//GEN-LAST:event_chResolverFinanceiroMousePressed

    private void chResolverFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chResolverFinanceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chResolverFinanceiroActionPerformed

    private void tfValorEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfValorEntradaKeyReleased
        if( tfValorEntrada.isEnabled() ) {
            
            if( !tfValorEntrada.getText().trim().equals("") ) {
                
                
               try{
                   
                float valor = RetornarNumeroFloat.floatTF( 
                tfValorEntrada, tfValorEntrada.getText().trim(), "Valor de entrada", true );
                            
                    if( valor > 0 ){
                
                        /********Verificar outros controle depois como nome do cliente e veículo*******/
                        if( valor < Total ) {
                            
                            OS.receber_e_SetarValorDeEntrada( valor );
                            setarParcelas( Home, OS, Total, OS.pegar_e_GetConta(), OS.pegar_e_GetDocumento(), OS.pegar_e_GetarFormaPgto() );
                        }
                        else{
                            
                            tfValorEntrada.setText("");
                            JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Valor de entrada "+ tfValorEntrada.getText().trim() 
                                    + "\n"
                                    + "\nO Valor de entrada não pode ser maior ou igual a " + Total    
                                    + "\n"
                                    + "\nPara continuar edite este valor"
                                    + "\n"
                                    , "Valor de entrada " );
                                tfValorEntrada.requestFocus();
                        }
                    }
                    else {
                        tfValorEntrada.setText("");
                        JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Valor de entrada "+ tfValorEntrada.getText().trim() 
                                    + "\n"
                                    + "\nO Valor de entrada não pode ser menor ou igual a  0"    
                                    + "\n"
                                    + "\nPara continuar edite este valor"
                                    + "\n"
                                    , "Valor de entrada " );
                                tfValorEntrada.requestFocus();  
                    }
                    }catch(Exception e) {
                        tfValorEntrada.setText("");
                        JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Valor de entrada "+ tfValorEntrada.getText().trim() 
                                    + "\n"
                                    + "\nO Valor de entrada não pode ser menor ou igual a  0"    
                                    + "\n"
                                    + "\nPara continuar edite este valor"
                                    + "\n"
                                    , "Valor de entrada " );
                                tfValorEntrada.requestFocus(); 
                    }     
            }            
        }
    }//GEN-LAST:event_tfValorEntradaKeyReleased

    private void tfValorDescontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfValorDescontoKeyReleased
        if( tfValorDesconto.isEnabled() ) {
            
            if( !tfValorDesconto.getText().trim().equals("") ) {
                
                
               try{
                   
                float valor = RetornarNumeroFloat.floatTF( 
                tfValorDesconto, tfValorDesconto.getText().trim(), "Valor de desconto", true );
                            
                    if( valor > 0 ){
                
                        float totalMenosEntrada = Total - OS.pegar_e_GetValorDeEntrada();
                        /********Verificar outros controle depois como nome do cliente e veículo*******/
                        if( valor < Total && valor < totalMenosEntrada ) {
                           
                            if( cbTipoDeDesconto.getSelectedItem() != null && cbTipoDeDesconto.isEnabled() ) {

                                String tipoDeDesconto = cbTipoDeDesconto.getSelectedItem().toString(); 
                                if( tipoDeDesconto.equals("Sem desconto") ){
                                                            
                                    OS.receber_e_SetarVALORDEDESCONTO ( 0 );
                                }
                                else if( tipoDeDesconto.equals("Desconto em porcentagem") ){
                                        
                                    float valorDesc = Total * ( valor/100 );
                                    if( valorDesc < totalMenosEntrada ){
                                        OS.receber_e_SetarVALORDEDESCONTO ( valorDesc ); 
                                    }
                                    else{
                                        tfValorDesconto.setText("");
                                        JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Valor de desconto "+ tfValorDesconto.getText().trim() 
                                            + "\n"
                                            + "\nO Valor de desconto não pode ser maior ou igual a " + totalMenosEntrada     
                                            + "\n"
                                            + "\nPara continuar edite este valor"
                                            + "\n"
                                            , "Valor de desconto " );
                                        tfValorDesconto.requestFocus();
                                    }
                                }
                                else{
                                                            
                                    OS.receber_e_SetarVALORDEDESCONTO ( valor );
                                }
                                
                                setarParcelas( Home, OS, Total, OS.pegar_e_GetConta(), OS.pegar_e_GetDocumento(), OS.pegar_e_GetarFormaPgto() );
                            }
                        }    
                        else{
                            
                            tfValorDesconto.setText("");
                            JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Valor de desconto "+ tfValorDesconto.getText().trim() 
                                    + "\n"
                                    + "\nO Valor de desconto não pode ser maior ou igual a " + totalMenosEntrada     
                                    + "\n"
                                    + "\nPara continuar edite este valor"
                                    + "\n"
                                    , "Valor de desconto " );
                                tfValorDesconto.requestFocus();
                        }
                    }
                    else {
                        tfValorDesconto.setText("");
                        JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Valor de desconto "+ tfValorDesconto.getText().trim() 
                                    + "\n"
                                    + "\nO Valor de entrada não pode ser menor ou igual a  0"    
                                    + "\n"
                                    + "\nPara continuar edite este valor"
                                    + "\n"
                                    , "Valor de desconto " );
                                tfValorDesconto.requestFocus();  
                    }
                    }catch(Exception e) {
                        tfValorDesconto.setText("");
                        JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "Valor de desconto "+ tfValorDesconto.getText().trim() 
                                    + "\n"
                                    + "\nO Valor de desconto não pode ser menor ou igual a  0"    
                                    + "\n"
                                    + "\nPara continuar edite este valor"
                                    + "\n"
                                    , "Valor de desconto " );
                                tfValorDesconto.requestFocus(); 
                    }     
            }            
        }
    }//GEN-LAST:event_tfValorDescontoKeyReleased
           
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Parcelas_OS_Definir_Forma_de_Pagamento;
    public javax.swing.JButton btAtualizar;
    public javax.swing.JButton btCancelar;
    public javax.swing.JButton btCancelar1;
    public javax.swing.JComboBox cbFormaDePagamento;
    public javax.swing.JComboBox cbParcelas;
    public javax.swing.JComboBox cbTipoDeDesconto;
    public javax.swing.JComboBox cbTipoDeEntrada;
    public javax.swing.JCheckBox chJuros;
    public javax.swing.JCheckBox chResolverFinanceiro;
    public javax.swing.JCheckBox chTaxaFixa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jpResolverProblema;
    public javax.swing.JLabel lbFormaDePagamento;
    public javax.swing.JLabel lbNomeDoValorDedesconto;
    public javax.swing.JLabel lbTotalEsquerdo;
    public javax.swing.JLabel lbValorAvista;
    public javax.swing.JTextField tfValorDesconto;
    public javax.swing.JTextField tfValorEntrada;
    // End of variables declaration//GEN-END:variables
   
    boolean permitirAcesso = false;
    private void configurarCbPermitirAcesso(){
        if( permitirAcesso == true ) {
            permitirAcesso = false;
            
            OS.receber_e_SetarFINANCEIRO( false );
            
           Parcelas_OS_Definir_Forma_de_Pagamento.setVisible( false );
          
        } else if( permitirAcesso == false ) {
            permitirAcesso = true;
            
            OS.receber_e_SetarFINANCEIRO( true );
            Parcelas_OS_Definir_Forma_de_Pagamento.setVisible( true );
        }
        
    }
  
}
