/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tipo_de_documento;

import home.Home;

/**
 *
 * @author AnaMariana
 */
public class Tipos_de_Documento_Home extends javax.swing.JPanel {
    
    Home Home;
    Tipo_de_Documento_Home_Inicio Tipo_de_Documento_Home_Inicio;
    
    public Tipos_de_Documento Tipos_de_Documento;
    public Tipo_de_Documentos_Botoes Tipo_de_Documentos_Botoes;

    /**
     * Creates new form Cliente
     * @param Home2
     */
    public Tipos_de_Documento_Home( Home Home2 ) {
        Home = Home2;
        
        initComponents();
       
        Tipo_de_Documento_Home_Inicio = new Tipo_de_Documento_Home_Inicio( Home, this);
        
        Tipo_de_Documento_Home_Inicio.inicio();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
             
}
